# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3

cache: 
  packages: TRUE

bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("BiocManager")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics", ref = "master")'
  
install:
  - R -e 'BiocManager::install("Rhdf5lib")'
  - R -e 'BiocManager::install("flowCore")'
  - R -e 'BiocManager::install("flowWorkspace")'
  - R -e 'BiocManager::install("openCyto")'
  - R -e 'devtools::install_github("RcppCore/RcppParallel", ref="master")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib")'
  - R -e 'devtools::install_github("RGLab/flowCore")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/flowWorkspace")'
  - R -e 'devtools::install_github("RGLab/flowStats", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/openCyto")'
  - R -e 'devtools::install_deps(upgrade = "Always")'
  
r_packages:
  - data.table
  - shiny
  - shinythemes
  - MASS
  - methods
  - stats
  - utils
  - graphics
  - grDevices
  - tools
  - magrittr
  - purrr
  - parallel
  - tibble
  - tidyr
  - dplyr
  - robustbase
  - Rtsne
  - umap    
  - gtools
  - flowAI
  - EmbedSOM

r_github_packages:
  - jrowen/rhandsontable
  - rlbarter/superheat
  - rstudio/rmarkdown
  - yihui/knitr
  - r-lib/covr
  - r-lib/testthat
  - r-lib/vdiffr
  - r-lib/pkgdown
  - datastorm-open/visNetwork
  - rstudio/shinytest
  - DillonHammill/CytoExploreRData
  
warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev
  