# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3
   - os: osx
     osx_image: xcode7.3
     disable_homebrew: true

cache: 
  packages: TRUE

before_install:
  - R -e 'install.packages("devtools")'

r_packages:
  - data.table
  - shiny
  - shinythemes
  - MASS
  - methods
  - stats
  - utils
  - magrittr
  - purrr
  - tibble
  - tidyr
  - dplyr
  - robustbase
  - gtools
  - Rtsne
  - umap
  - rmarkdown
  - robustbase

r_github_packages:
  - jrowen/rhandsontable
  - rlbarter/superheat
  - yihui/knitr
  - r-lib/covr
  - r-lib/testthat
  - r-lib/vdiffr
  - r-lib/pkgdown
  - datastorm-open/visNetwork
  - rstudio/shinytest
  - DillonHammill/CytoExploreRData
  
use_bioc: true

bioc_packages:
  - BiocGenerics
  - RProtoBufLib
  - flowCore
  - ncdfFlow
  - cytolib
  - flowWorkspace
  - openCyto
  
warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev
  