# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3

cache: 
  packages: true

bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("BiocManager")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics")'

install:
  - R -e 'BiocManager::install("Rhdf5lib")'
  - R -e 'devtools::install_github("RcppCore/RcppParallel")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib")'
  - R -e 'devtools::install_github("RGLab/flowCore")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/flowWorkspace")'
  - R -e 'devtools::install_github("RGLab/flowStats", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/openCyto", ref = "trunk")'
  - R -e 'BiocManager::install("flowAI")'
  - R -e 'utils::install.packages("EmbedSOM")'
  - R -e 'devtools::install_github("DillonHammill/CytoExploreRData")'
  - R -e 'devtools::install_github("rstudio/shinythemes")'
  - R -e 'devtools::install_github("jrowen/rhandsontable")'
  - R -e 'devtools::install_github("rlbarter/superheat")'
  - R -e 'devtools::install_github("datastorm-open/visNetwork")'
  - R -e 'devtools::install_github("tidyverse/tidyr")'
  - R -e 'devtools::install_github("r-lib/mockery")'
  - R -e 'devtools::install_github("r-lib/covr")'
  
# Turn off slow processes to allow package caching on build success
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-tests --no-vignettes --no-manual --no-examples

warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev