# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3

cache: 
  packages: true

bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("BiocManager")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics")'
  
install:
  - R -e 'BiocManager::install("Rhdf5lib")'
  - R -e 'devtools::install_github("rlbarter/superheat")'
  - R -e 'devtools::install_github("datastorm-open/visNetwork")'
  - R -e 'devtools::install_github("RcppCore/RcppParallel")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib")'
  - R -e 'devtools::install_github("RGLab/flowCore")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/flowWorkspace")'
  - R -e 'devtools::install_github("RGLab/flowStats", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/openCyto", ref = "trunk")'
  - R -e 'BiocManager::install("flowAI")'
  - R -e 'devtools::install_github("DillonHammill/CytoExploreRData")'
  - R -e 'devtools::install_github("r-lib/vdiffr")'
  - R -e 'devtools::install_github("r-lib/pkgdown")'
  - R -e 'devtools::install_github("r-lib/mockery")'
  - R -e 'devtools::install_github("rstudio/shinytest")'
  - R -e 'devtools::install_deps(upgrade = "always")'
  
r_packages:
  - data.table
  - shiny
  - shinythemes
  - shinytest
  - MASS
  - methods
  - stats
  - utils
  - graphics
  - grDevices
  - tools
  - magrittr
  - purrr
  - parallel
  - tibble
  - tidyr
  - dplyr
  - robustbase
  - Rtsne
  - umap    
  - gtools
  - rhandsontable
  - EmbedSOM
  - mockery
  - pkgdown
  - vdiffr

r_github_packages:
  - rstudio/rmarkdown
  - yihui/knitr
  - r-lib/covr
  - r-lib/testthat
  
warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev