# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: required

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
     env: R_CODECOV=true
   - os: osx
     osx_image: xcode9.3

cache: 
  packages: true

bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("BiocManager")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics")'
  
r_packages:
  - data.table
  - dplyr
  - graphics  
  - grDevices
  - gtools
  - magrittr
  - methods
  - mockery
  - parallel
  - pkgdown
  - purrr
  - rhandsontable
  - robustbase
  - Rtsne
  - shiny
  - shinythemes
  - shinytest
  - stats  
  - tibble    
  - tidyr
  - tools
  - umap
  - utils
  - vdiffr

r_github_packages:
  - r-lib/covr
  - yihui/knitr
  - r-lib/mockery
  - r-lib/pkgdown
  - rstudio/rmarkdown
  - rlbarter/superheat
  - r-lib/testthat
  - datastom-open/visNetwork
  
install:
  - R -e 'BiocManager::install("Rhdf5lib")'
  - R -e 'devtools::install_github("RcppCore/RcppParallel")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib")'
  - R -e 'devtools::install_github("RGLab/flowCore")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/flowWorkspace")'
  - R -e 'devtools::install_github("RGLab/flowStats", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/openCyto", ref = "trunk")'
  - R -e 'BiocManager::install("flowAI")'
  - R -e 'utils::install.packages("EmbedSOM")'
  - R -e 'devtools::install_github("DillonHammill/CytoExploreRData")'
  
warnings_are_errors: false

after_success:
  -  if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
env:
 global:
   - CRAN: http://cran.rstudio.com
   - BIOC_USE_DEVEL="FALSE"

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev