app <- ShinyDriver$new("../", loadTimeout = 1e+05)
app$snapshotInit("spillover_edit")

app$setInputs(flowFrame = "PE-Cy7.fcs")
app$snapshot()
app$setInputs(ychannel = "APC-Cy7-A")
app$snapshot()
app$setInputs(NIL = FALSE)
app$snapshot()
app$setInputs(median = FALSE)
app$snapshot()
app$setInputs(trace = FALSE)
app$snapshot()
app$snapshot()
app$setInputs(NIL2 = FALSE)
app$snapshot()
app$setInputs(Comp = FALSE)
app$snapshot()
app$setInputs(Comp = TRUE)
app$setInputs(NIL2 = TRUE)
app$setInputs(flowFrame2 = "APC-Cy7.fcs")
app$snapshot()
