<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Getting Started with CytoRSuite • CytoRSuite</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Getting Started with CytoRSuite">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">CytoRSuite</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/CytoRSuite.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/CytoRSuite-Compensation.html">CytoRSuite: Compensation of Fluorescent Spillover</a>
    </li>
    <li>
      <a href="../articles/CytoRSuite-Gate-Manipulation.html">CytoRSuite: Gate Manipulation</a>
    </li>
    <li>
      <a href="../articles/CytoRSuite-Gating-Functions.html">CytoRSuite: Gating Functions</a>
    </li>
    <li>
      <a href="../articles/CytoRSuite-Manual-Automated-Gating.html">CytoRSuite: Manual and Automated Gating</a>
    </li>
    <li>
      <a href="../articles/CytoRSuite-Visualisation.html">CytoRSuite: Visualisation Using cyto_plot</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/DillonHammill/CytoRSuite">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Getting Started with CytoRSuite</h1>
                        <h4 class="author">Dillon Hammill</h4>
            
            <h4 class="date">2019-03-30</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/DillonHammill/CytoRSuite/blob/master/vignettes/CytoRSuite.Rmd"><code>vignettes/CytoRSuite.Rmd</code></a></small>
      <div class="hidden name"><code>CytoRSuite.Rmd</code></div>

    </div>

    
    
<div id="overview" class="section level1">
<h1 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h1>
<p>The main features of CytoRSuite will be documented in separate vignettes for “Compensation”, “Gating functions”, “Visualisation” and “Manual and Automated gating” respectively. Before we dive into the details, let’s demonstrate how simple it can be to analyse some in vitro T cell activation data using <strong>CytoRSuite</strong>. The Activation dataset used in this vignette is shipped with CytoRSuiteData. For more details on this dataset see <strong>?Activation</strong>.</p>
<div id="load-required-packages" class="section level2">
<h2 class="hasAnchor">
<a href="#load-required-packages" class="anchor"></a>1. Load Required Packages</h2>
<p>Loading CytoRSuite will automatically load <code>flowCore</code>, <code>flowWorkspace</code> and <code>openCyto</code> which will be required at various stages throughout the analysis process.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(CytoRSuite)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(CytoRSuiteData)</a></code></pre></div>
</div>
<div id="explore-activation-dataset" class="section level2">
<h2 class="hasAnchor">
<a href="#explore-activation-dataset" class="anchor"></a>2. Explore Activation Dataset</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="co"># Activation is a flowSet containing 4 samples</span></a>
<a class="sourceLine" id="cb2-2" title="2">Activation</a>
<a class="sourceLine" id="cb2-3" title="3"></a>
<a class="sourceLine" id="cb2-4" title="4"><span class="co"># Individual samples can be extracted as flowFrames using [[]]</span></a>
<a class="sourceLine" id="cb2-5" title="5">Activation[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb2-6" title="6"></a>
<a class="sourceLine" id="cb2-7" title="7"><span class="co"># Raw data for each flowFrame is stored in exprs slot</span></a>
<a class="sourceLine" id="cb2-8" title="8">Activation[[<span class="dv">1</span>]]<span class="op">@</span>exprs</a>
<a class="sourceLine" id="cb2-9" title="9"></a>
<a class="sourceLine" id="cb2-10" title="10"><span class="co"># Information is attached to each flowFrame in description slot</span></a>
<a class="sourceLine" id="cb2-11" title="11">Activation[[<span class="dv">1</span>]]<span class="op">@</span>description</a>
<a class="sourceLine" id="cb2-12" title="12"></a>
<a class="sourceLine" id="cb2-13" title="13"><span class="co"># Spillover matrix can be extracted from description slot</span></a>
<a class="sourceLine" id="cb2-14" title="14">Activation[[<span class="dv">1</span>]]<span class="op">@</span>description<span class="op">$</span>SPILL</a>
<a class="sourceLine" id="cb2-15" title="15"></a>
<a class="sourceLine" id="cb2-16" title="16"><span class="co"># Experimental information is stored in pData</span></a>
<a class="sourceLine" id="cb2-17" title="17"><span class="kw">pData</span>(Activation)</a>
<a class="sourceLine" id="cb2-18" title="18"></a>
<a class="sourceLine" id="cb2-19" title="19"><span class="co"># Assign Activation to fs for brevity</span></a>
<a class="sourceLine" id="cb2-20" title="20">fs &lt;-<span class="st"> </span>Activation</a></code></pre></div>
</div>
<div id="annotate-flowset-with-markers" class="section level2">
<h2 class="hasAnchor">
<a href="#annotate-flowset-with-markers" class="anchor"></a>3. Annotate flowSet with Markers</h2>
<p>Assigning marker names to channels will be useful downstream as we can refer to channels by their marker rather than by name. <code>cyto_markers</code> provides an editable table to make marker assignment easy. The details in the flowSet will automatically be updated when the window is closed. Channels without markers should have empty “Marker” entries. Edit the table to match the image below:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="co"># Assign markers</span></a>
<a class="sourceLine" id="cb3-2" title="2"><span class="kw"><a href="../reference/cyto_markers.html">cyto_markers</a></span>(fs)</a></code></pre></div>
<p><img src="cyto_markers.png" width="30%" height="30%" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="co"># Markers added to desc column in details for each flowFrame</span></a>
<a class="sourceLine" id="cb4-2" title="2">fs[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb4-3" title="3"><span class="co">#&gt; flowFrame object 'Activation1.fcs'</span></a>
<a class="sourceLine" id="cb4-4" title="4"><span class="co">#&gt; with 50000 cells and 18 observables:</span></a>
<a class="sourceLine" id="cb4-5" title="5"><span class="co">#&gt;                   name        desc  range minRange maxRange</span></a>
<a class="sourceLine" id="cb4-6" title="6"><span class="co">#&gt; $P1              FSC-A        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-7" title="7"><span class="co">#&gt; $P2              FSC-H        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-8" title="8"><span class="co">#&gt; $P3              FSC-W        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-9" title="9"><span class="co">#&gt; $P4              SSC-A        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-10" title="10"><span class="co">#&gt; $P5              SSC-H        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-11" title="11"><span class="co">#&gt; $P6              SSC-W        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-12" title="12"><span class="co">#&gt; $P7  Alexa Fluor 488-A         CD8 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-13" title="13"><span class="co">#&gt; $P8               PE-A         Va2 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-14" title="14"><span class="co">#&gt; $P9     PE-Texas Red-A        &lt;NA&gt; 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-15" title="15"><span class="co">#&gt; $P10           7-AAD-A        CD69 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-16" title="16"><span class="co">#&gt; $P11          PE-Cy7-A        &lt;NA&gt; 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-17" title="17"><span class="co">#&gt; $P12 Alexa Fluor 405-A Hoechst-405 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-18" title="18"><span class="co">#&gt; $P13 Alexa Fluor 430-A Hoechst-430 262144   -86.64   262144</span></a>
<a class="sourceLine" id="cb4-19" title="19"><span class="co">#&gt; $P14        Qdot 605-A        &lt;NA&gt; 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-20" title="20"><span class="co">#&gt; $P15 Alexa Fluor 647-A        CD44 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-21" title="21"><span class="co">#&gt; $P16 Alexa Fluor 700-A         CD4 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-22" title="22"><span class="co">#&gt; $P17         APC-Cy7-A       CD11c 262144  -111.00   262144</span></a>
<a class="sourceLine" id="cb4-23" title="23"><span class="co">#&gt; $P18              Time        &lt;NA&gt; 262144     0.00   262144</span></a>
<a class="sourceLine" id="cb4-24" title="24"><span class="co">#&gt; 261 keywords are stored in the 'description' slot</span></a></code></pre></div>
</div>
<div id="annotate-flowset-with-experimental-details" class="section level2">
<h2 class="hasAnchor">
<a href="#annotate-flowset-with-experimental-details" class="anchor"></a>4. Annotate flowSet with Experimental Details</h2>
<p>Experimental details can be associated with each sample using <code>cyto_annotate</code> which uses the same interface as <code>cyto_markers</code> to interactively edit pData information. This information will be used downstream for grouping samples prior to gating and will be included in the exported statistics tables to aid in statistical analysis. Modify the table to include a variable “OVAConc” with values 0, 0.005, 0.05 and 0.5 as shown in the image.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="co"># Associate each samples with experimental information</span></a>
<a class="sourceLine" id="cb5-2" title="2"><span class="kw"><a href="../reference/cyto_annotate.html">cyto_annotate</a></span>(fs)</a></code></pre></div>
<p><img src="cyto_annotate.png" width="30%" height="30%" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="co"># pData information updated with OVAConc column</span></a>
<a class="sourceLine" id="cb6-2" title="2"><span class="kw">pData</span>(fs)</a>
<a class="sourceLine" id="cb6-3" title="3"><span class="co">#&gt;                            name OVAConc</span></a>
<a class="sourceLine" id="cb6-4" title="4"><span class="co">#&gt; Activation1.fcs Activation1.fcs   0.000</span></a>
<a class="sourceLine" id="cb6-5" title="5"><span class="co">#&gt; Activation2.fcs Activation2.fcs   0.005</span></a>
<a class="sourceLine" id="cb6-6" title="6"><span class="co">#&gt; Activation3.fcs Activation3.fcs   0.050</span></a>
<a class="sourceLine" id="cb6-7" title="7"><span class="co">#&gt; Activation4.fcs Activation4.fcs   0.500</span></a></code></pre></div>
</div>
<div id="add-samples-to-gatingset-for-gating" class="section level2">
<h2 class="hasAnchor">
<a href="#add-samples-to-gatingset-for-gating" class="anchor"></a>5. Add Samples to GatingSet for Gating</h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">gs &lt;-<span class="st"> </span><span class="kw">GatingSet</span>(fs)</a>
<a class="sourceLine" id="cb7-2" title="2"></a>
<a class="sourceLine" id="cb7-3" title="3"><span class="co"># GatingSet inherits pData information</span></a>
<a class="sourceLine" id="cb7-4" title="4"><span class="kw">pData</span>(gs)</a>
<a class="sourceLine" id="cb7-5" title="5"><span class="co">#&gt;                            name OVAConc</span></a>
<a class="sourceLine" id="cb7-6" title="6"><span class="co">#&gt; Activation1.fcs Activation1.fcs   0.000</span></a>
<a class="sourceLine" id="cb7-7" title="7"><span class="co">#&gt; Activation2.fcs Activation2.fcs   0.005</span></a>
<a class="sourceLine" id="cb7-8" title="8"><span class="co">#&gt; Activation3.fcs Activation3.fcs   0.050</span></a>
<a class="sourceLine" id="cb7-9" title="9"><span class="co">#&gt; Activation4.fcs Activation4.fcs   0.500</span></a></code></pre></div>
</div>
<div id="apply-compensation" class="section level2">
<h2 class="hasAnchor">
<a href="#apply-compensation" class="anchor"></a>6. Apply Compensation</h2>
<p>CytoRSuite provides three distinct functions to aid in compensation of fluorescence spillover:</p>
<ul>
<li>
<code>spillover_compute</code> provides an automated approach to calculating the percentage of fluorescent spillover using the algorithm described by Bagwell &amp; Adams 1993.</li>
<li>
<code>spillover_edit</code> utilises an interactive Shiny interface to allow realtime visualisation of changes in spillover percentages and is designed to aid in manual manipulation of spillover matrices.</li>
<li>
<code>cyto_plot_compensation</code> displays each compensation control in all channels to easily identify any potential compensation issues.</li>
</ul>
<p>These features will be documented in a separate compensation vignette, see <code><a href="../reference/spillover_compute.html">?spillover_compute</a></code>, <code><a href="../reference/spillover_edit.html">?spillover_edit</a></code> and <code><a href="../reference/cyto_plot_compensation.html">?cyto_plot_compensation</a></code> for more details on these functions.</p>
<p>Here we will demonstrate how to apply the spillover matrix attached to each flowFrame. Recall the spillover matrix can be extracted from the <code>description</code> slot of the flowFrame under <code>SPILL</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="co"># Get attached spillover matrix</span></a>
<a class="sourceLine" id="cb8-2" title="2">spill &lt;-<span class="st"> </span>fs[[<span class="dv">1</span>]]<span class="op">@</span>description<span class="op">$</span>SPILL</a>
<a class="sourceLine" id="cb8-3" title="3">spill</a>
<a class="sourceLine" id="cb8-4" title="4"><span class="co">#&gt;       Alexa Fluor 488-A       PE-A PE-Texas Red-A    7-AAD-A    PE-Cy7-A</span></a>
<a class="sourceLine" id="cb8-5" title="5"><span class="co">#&gt;  [1,]       1.000000000 0.18800066   0.0840010055 0.01800011 0.000000000</span></a>
<a class="sourceLine" id="cb8-6" title="6"><span class="co">#&gt;  [2,]       0.006000035 1.00000000   0.5230093475 0.16800103 0.028000168</span></a>
<a class="sourceLine" id="cb8-7" title="7"><span class="co">#&gt;  [3,]       0.000000000 0.00000000   1.0000000000 0.00000000 0.000000000</span></a>
<a class="sourceLine" id="cb8-8" title="8"><span class="co">#&gt;  [4,]       0.000000000 0.00000000   0.0000556259 1.00000000 0.310001025</span></a>
<a class="sourceLine" id="cb8-9" title="9"><span class="co">#&gt;  [5,]       0.000000000 0.00000000   0.0000000000 0.00000000 1.000000000</span></a>
<a class="sourceLine" id="cb8-10" title="10"><span class="co">#&gt;  [6,]       0.000000000 0.00000000   0.0000000000 0.00000000 0.000000000</span></a>
<a class="sourceLine" id="cb8-11" title="11"><span class="co">#&gt;  [7,]       0.000000000 0.00000000   0.0000000000 0.00000000 0.000000000</span></a>
<a class="sourceLine" id="cb8-12" title="12"><span class="co">#&gt;  [8,]       0.000000000 0.00000000   0.0000000000 0.00000000 0.000000000</span></a>
<a class="sourceLine" id="cb8-13" title="13"><span class="co">#&gt;  [9,]       0.000000000 0.00000000   0.0000000000 0.02600016 0.008000026</span></a>
<a class="sourceLine" id="cb8-14" title="14"><span class="co">#&gt; [10,]       0.000000000 0.00000000   0.0000000000 0.04100026 0.049000041</span></a>
<a class="sourceLine" id="cb8-15" title="15"><span class="co">#&gt; [11,]       0.016000008 0.01000058   0.0120008920 0.01600009 0.088000019</span></a>
<a class="sourceLine" id="cb8-16" title="16"><span class="co">#&gt;       Alexa Fluor 405-A Alexa Fluor 430-A  Qdot 605-A Alexa Fluor 647-A</span></a>
<a class="sourceLine" id="cb8-17" title="17"><span class="co">#&gt;  [1,]        0.00000000        0.01400073 0.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-18" title="18"><span class="co">#&gt;  [2,]        0.00000000        0.00000000 0.132000815       0.000000000</span></a>
<a class="sourceLine" id="cb8-19" title="19"><span class="co">#&gt;  [3,]        0.00000000        0.00000000 0.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-20" title="20"><span class="co">#&gt;  [4,]        0.00000000        0.00000000 0.000000000       0.005999995</span></a>
<a class="sourceLine" id="cb8-21" title="21"><span class="co">#&gt;  [5,]        0.00000000        0.00000000 0.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-22" title="22"><span class="co">#&gt;  [6,]        1.00000000        0.00000000 0.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-23" title="23"><span class="co">#&gt;  [7,]        0.00000000        1.00000000 0.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-24" title="24"><span class="co">#&gt;  [8,]        0.00000000        0.00000000 1.000000000       0.000000000</span></a>
<a class="sourceLine" id="cb8-25" title="25"><span class="co">#&gt;  [9,]        0.00000000        0.00000000 0.003000122       1.000000000</span></a>
<a class="sourceLine" id="cb8-26" title="26"><span class="co">#&gt; [10,]        0.00000000        0.00000000 0.000000000       0.004000004</span></a>
<a class="sourceLine" id="cb8-27" title="27"><span class="co">#&gt; [11,]        0.01199991        0.00800065 0.019000078       0.032000004</span></a>
<a class="sourceLine" id="cb8-28" title="28"><span class="co">#&gt;       Alexa Fluor 700-A APC-Cy7-A</span></a>
<a class="sourceLine" id="cb8-29" title="29"><span class="co">#&gt;  [1,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-30" title="30"><span class="co">#&gt;  [2,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-31" title="31"><span class="co">#&gt;  [3,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-32" title="32"><span class="co">#&gt;  [4,]        0.03699999     0.015</span></a>
<a class="sourceLine" id="cb8-33" title="33"><span class="co">#&gt;  [5,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-34" title="34"><span class="co">#&gt;  [6,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-35" title="35"><span class="co">#&gt;  [7,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-36" title="36"><span class="co">#&gt;  [8,]        0.00000000     0.000</span></a>
<a class="sourceLine" id="cb8-37" title="37"><span class="co">#&gt;  [9,]        0.35900000     0.090</span></a>
<a class="sourceLine" id="cb8-38" title="38"><span class="co">#&gt; [10,]        1.00000000     0.270</span></a>
<a class="sourceLine" id="cb8-39" title="39"><span class="co">#&gt; [11,]        0.11400001     1.000</span></a>
<a class="sourceLine" id="cb8-40" title="40"></a>
<a class="sourceLine" id="cb8-41" title="41"><span class="co"># Compensate samples with spill</span></a>
<a class="sourceLine" id="cb8-42" title="42">gs &lt;-<span class="st"> </span><span class="kw">compensate</span>(gs, spill)</a></code></pre></div>
</div>
<div id="transform-fluorescent-channels" class="section level2">
<h2 class="hasAnchor">
<a href="#transform-fluorescent-channels" class="anchor"></a>7. Transform Fluorescent Channels</h2>
<p>In order to appropriately visualise the data, we first need to transform all fluorescent channels post-compensation. Currently, CytoRSuite only supports the <code>logicle</code> transformation documented in the flowCore package. Below we use <code>estimateLogicle</code> to get parameter estimates for each fluorescent channel and apply these transformations to the GatingSet using the <code>transform</code> function from flowCore.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="co"># Get a list of the fluorescent channels</span></a>
<a class="sourceLine" id="cb9-2" title="2">channels &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cyto_fluor_channels.html">cyto_fluor_channels</a></span>(gs)</a>
<a class="sourceLine" id="cb9-3" title="3"></a>
<a class="sourceLine" id="cb9-4" title="4">trans &lt;-<span class="st"> </span><span class="kw">estimateLogicle</span>(gs[[<span class="dv">2</span>]], channels)</a>
<a class="sourceLine" id="cb9-5" title="5">gs &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/transform">transform</a></span>(gs, trans)</a></code></pre></div>
</div>
<div id="visualise-gatingset-using-cyto_plot" class="section level2">
<h2 class="hasAnchor">
<a href="#visualise-gatingset-using-cyto_plot" class="anchor"></a>8. Visualise GatingSet using <code>cyto_plot</code>
</h2>
<p>Visualising 1-D density distributions and 2-D scatter plots of flow cytometry data is made easy with <code>cyto_plot</code>. <code>cyto_plot</code> is capable of handling flowFrame, flowSet, GatingHierarchy and GatingSet objects. Any function in CytoRSuite which makes a call to plot uses <code>cyto_plot</code> internally and can therefore accept any of its arguments to customise the plot output. In a similar fashion to ggplot2, <code>cyto_plot</code> has arguments of the form geom_aes (e.g. point_col) which make it autocomplete friendly. Additional plotting functions such as <code>cyto_plot_profile</code> and <code>cyto_plot_gating_scheme</code> allow the user to look at expression profiles and gating schemes respectively. All these visualisation tools will be detailed in the “Visualisation” vignette.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="co"># 2-D scatter plot with contour lines</span></a>
<a class="sourceLine" id="cb10-2" title="2"><span class="kw"><a href="../reference/cyto_plot.html">cyto_plot</a></span>(gs,</a>
<a class="sourceLine" id="cb10-3" title="3">          <span class="dt">parent =</span> <span class="st">"root"</span>,</a>
<a class="sourceLine" id="cb10-4" title="4">          <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD4"</span>,<span class="st">"CD8"</span>),</a>
<a class="sourceLine" id="cb10-5" title="5">          <span class="dt">group_by =</span> <span class="st">"all"</span>,</a>
<a class="sourceLine" id="cb10-6" title="6">          <span class="dt">contour_lines =</span> <span class="dv">15</span>)</a>
<a class="sourceLine" id="cb10-7" title="7"></a>
<a class="sourceLine" id="cb10-8" title="8"><span class="co">#1-D stacked density distributions</span></a>
<a class="sourceLine" id="cb10-9" title="9"><span class="kw"><a href="../reference/cyto_plot.html">cyto_plot</a></span>(gs,</a>
<a class="sourceLine" id="cb10-10" title="10">          <span class="dt">parent =</span> <span class="st">"root"</span>,</a>
<a class="sourceLine" id="cb10-11" title="11">          <span class="dt">channels =</span> <span class="st">"CD8"</span>,</a>
<a class="sourceLine" id="cb10-12" title="12">          <span class="dt">density_stack =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-15-1.png" width="672"></p>
</div>
<div id="draw-gates-using-gate_draw-to-complete-the-gating-scheme" class="section level2">
<h2 class="hasAnchor">
<a href="#draw-gates-using-gate_draw-to-complete-the-gating-scheme" class="anchor"></a>9. Draw Gates Using <code>gate_draw</code> to Complete the Gating Scheme</h2>
<p><code>gate_draw</code> is a convenient wrapper for the gating functions in CytoRSuite which constructs drawn gates, applies the gate(s) directly to the <code>GatingSet</code> and saves the gate(s) to an <code>openCyto gatingTemplate</code> csv file for future use. <code>gate_draw</code> will pool the data based on <code>group_by</code> and plot it in an interactive plotting window which will allow the user to draw gates around the population of interest. The type of gate is determined by the <code>type</code> argument. Below we will demonstrate some of the key features of gate_draw, for details on specific gate types please refer to the gating functions vignette.</p>
<div id="gate-cells-using-a-polygon-gate" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-cells-using-a-polygon-gate" class="anchor"></a>9.1 Gate <code>Cells</code> Using a Polygon Gate</h3>
<p>Here we will gate a population “Cells” within the parent population “root” in FSC-A and SSC-A channels using a polygon gate. Polygon gates can be closed by right clicking and selecting “stop”. The gate will be automatically applied to the GatingSet and saved in a gatingTemplate csv called “Example gatingTemplate.csv” in the current working directory.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="co"># Cells</span></a>
<a class="sourceLine" id="cb11-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb11-3" title="3">         <span class="dt">parent =</span> <span class="st">"root"</span>, </a>
<a class="sourceLine" id="cb11-4" title="4">         <span class="dt">alias =</span> <span class="st">"Cells"</span>, </a>
<a class="sourceLine" id="cb11-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"FSC-A"</span>,<span class="st">"SSC-A"</span>), </a>
<a class="sourceLine" id="cb11-6" title="6">         <span class="dt">type =</span> <span class="st">"polygon"</span>, </a>
<a class="sourceLine" id="cb11-7" title="7">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-18-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-single-cells-using-a-polygon-gate" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-single-cells-using-a-polygon-gate" class="anchor"></a>9.2 Gate <code>Single Cells</code> Using a Polygon Gate</h3>
<p>Here we will gate a population “Single Cells” within the parent population “Cells” in FSC-A and FSC-H channels using a polygon gate. Notice how this gate is added as a row to the gatingTemplate csv file. Let’s make the points black and add some transparency to get an idea of point density.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="co"># Single Cells</span></a>
<a class="sourceLine" id="cb12-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb12-3" title="3">         <span class="dt">parent =</span> <span class="st">"Cells"</span>, </a>
<a class="sourceLine" id="cb12-4" title="4">         <span class="dt">alias =</span> <span class="st">"Single Cells"</span>, </a>
<a class="sourceLine" id="cb12-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"FSC-A"</span>,<span class="st">"FSC-H"</span>), </a>
<a class="sourceLine" id="cb12-6" title="6">         <span class="dt">type =</span> <span class="st">"polygon"</span>, </a>
<a class="sourceLine" id="cb12-7" title="7">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>,</a>
<a class="sourceLine" id="cb12-8" title="8">         <span class="dt">point_col =</span> <span class="st">"black"</span>,</a>
<a class="sourceLine" id="cb12-9" title="9">         <span class="dt">point_alpha =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-20-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-live-cells-using-polygon-gate" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-live-cells-using-polygon-gate" class="anchor"></a>9.3 Gate <code>Live Cells</code> Using Polygon Gate</h3>
<p>Here we will gate a population “Live Cells” within the parent population “Single Cells” in Alexa Fluor 405-A and Alexa Fluor 430-A channels using a polygon gate. Notice how the axes have been transformed appropriately on the plot as these fluorescent channels were transformed with the logicle transformation earlier.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="co"># Live Cells</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb13-3" title="3">         <span class="dt">parent =</span> <span class="st">"Single Cells"</span>, </a>
<a class="sourceLine" id="cb13-4" title="4">         <span class="dt">alias =</span> <span class="st">"Live Cells"</span>, </a>
<a class="sourceLine" id="cb13-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"Alexa Fluor 405-A"</span>,<span class="st">"Alexa Fluor 430-A"</span>), </a>
<a class="sourceLine" id="cb13-6" title="6">         <span class="dt">type =</span> <span class="st">"polygon"</span>, </a>
<a class="sourceLine" id="cb13-7" title="7">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-22-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-dendritic-cells-and-t-cells-using-rectangle-and-ellipsoid-gates" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-dendritic-cells-and-t-cells-using-rectangle-and-ellipsoid-gates" class="anchor"></a>9.4 Gate <code>Dendritic Cells</code> and <code>T Cells</code> Using Rectangle and Ellipsoid Gates</h3>
<p>Next we will demonstrate the ability to draw multiple gates (of the same or different type) onto the same plot. Here we will gate both the “Dendritic Cells” and “T Cells” populations within the parent population “Live Cells” in APC-Cy7-A and PE-A channels using a rectangle and an ellipsoid gate. To gate multiple populations on the same plot simply supply multiple names to the alias argument wrapped inside c(). Notice how we can use the marker names rather than the channel names since we assigned these using <code>cyto_markers</code>. Ellipsoid gates require selection of 4 points whilst rectangle gates require selection of 2 diagonal points to define the limits of the gate in 2 dimensions.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="co"># Dendritic Cells &amp; T cells</span></a>
<a class="sourceLine" id="cb14-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb14-3" title="3">         <span class="dt">parent =</span> <span class="st">"Live Cells"</span>, </a>
<a class="sourceLine" id="cb14-4" title="4">         <span class="dt">alias =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"Dendritic Cells"</span>, <span class="st">"T Cells"</span>), </a>
<a class="sourceLine" id="cb14-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD11c"</span>,<span class="st">"Va2"</span>), </a>
<a class="sourceLine" id="cb14-6" title="6">         <span class="dt">type =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"rectangle"</span>,<span class="st">"ellipse"</span>), </a>
<a class="sourceLine" id="cb14-7" title="7">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-24-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-cd4-t-cells-and-cd8-t-cells-using-rectangle-gates" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-cd4-t-cells-and-cd8-t-cells-using-rectangle-gates" class="anchor"></a>9.5 Gate <code>CD4 T Cells</code> and <code>CD8 T Cells</code> Using Rectangle Gates</h3>
<p>Here we will gate both the “CD4 T Cells” and “CD8 T Cells” populations within the parent population “T Cells” in Alexa Fluor 700-A and Alexa Fluor 488-A channels using a rectangle gates. Notice how gate type can also be abbreviated as the first letter of the gate type (e.g. “r” for “rectangle”). Be sure to draw the gates in the order that they are listed in the alias argument.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="co"># CD4 &amp; CD8 T Cells</span></a>
<a class="sourceLine" id="cb15-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb15-3" title="3">         <span class="dt">parent =</span> <span class="st">"T Cells"</span>, </a>
<a class="sourceLine" id="cb15-4" title="4">         <span class="dt">alias =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD4 T Cells"</span>, <span class="st">"CD8 T Cells"</span>), </a>
<a class="sourceLine" id="cb15-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD4"</span>,<span class="st">"CD8"</span>), </a>
<a class="sourceLine" id="cb15-6" title="6">         <span class="dt">type =</span> <span class="st">"r"</span>, </a>
<a class="sourceLine" id="cb15-7" title="7">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-26-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-cd69-cd4-t-cells-using-interval-gate" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-cd69-cd4-t-cells-using-interval-gate" class="anchor"></a>9.6 Gate <code>CD69+ CD4 T Cells</code> Using Interval Gate</h3>
<p>Here we will demonstrate the use of a different gate_type called “interval” which gates populations based on a defined lower and upper bound. Interval gates are traditionally used in a single dimension, but interval gates are fully supported for 2-dimensional plots on either the x or y axis. Notice how we have indicated which axis we would like to gate using the axis argument. In this case we will be gating the population based on a lower and upper y axis bounds. We will also add some contour lines to aid in gating.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="co"># CD69+ CD4 T Cells</span></a>
<a class="sourceLine" id="cb16-2" title="2"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb16-3" title="3">         <span class="dt">parent =</span> <span class="st">"CD4 T Cells"</span>, </a>
<a class="sourceLine" id="cb16-4" title="4">         <span class="dt">alias =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD69+ CD4 T Cells"</span>), </a>
<a class="sourceLine" id="cb16-5" title="5">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD44"</span>,<span class="st">"CD69"</span>), </a>
<a class="sourceLine" id="cb16-6" title="6">         <span class="dt">type =</span> <span class="st">"interval"</span>, </a>
<a class="sourceLine" id="cb16-7" title="7">         <span class="dt">axis =</span> <span class="st">"y"</span>, </a>
<a class="sourceLine" id="cb16-8" title="8">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>,</a>
<a class="sourceLine" id="cb16-9" title="9">         <span class="dt">contour_lines =</span> <span class="dv">15</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-28-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="gate-cd69-cd8-t-cells-using-interval-gate" class="section level3">
<h3 class="hasAnchor">
<a href="#gate-cd69-cd8-t-cells-using-interval-gate" class="anchor"></a>9.7 Gate <code>CD69+ CD8 T Cells</code> Using Interval Gate</h3>
<p>To finish things off lets make a similar gate on the CD8 T Cells as well. This time we will overlay the unactivated control in black and use it to determine where gate should be drawn.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="co"># Extract the CD8 T Cells from Sample 1 for overlay</span></a>
<a class="sourceLine" id="cb17-2" title="2">CD8 &lt;-<span class="st"> </span><span class="kw">getData</span>(gs, <span class="st">"CD8 T Cells"</span>)[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb17-3" title="3"></a>
<a class="sourceLine" id="cb17-4" title="4"><span class="co"># CD69+ CD8 T Cells</span></a>
<a class="sourceLine" id="cb17-5" title="5"><span class="kw"><a href="../reference/gate_draw.html">gate_draw</a></span>(gs, </a>
<a class="sourceLine" id="cb17-6" title="6">         <span class="dt">parent =</span> <span class="st">"CD8 T Cells"</span>, </a>
<a class="sourceLine" id="cb17-7" title="7">         <span class="dt">alias =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD69+ CD8 T Cells"</span>), </a>
<a class="sourceLine" id="cb17-8" title="8">         <span class="dt">channels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"CD44"</span>,<span class="st">"CD69"</span>), </a>
<a class="sourceLine" id="cb17-9" title="9">         <span class="dt">type =</span> <span class="st">"interval"</span>, </a>
<a class="sourceLine" id="cb17-10" title="10">         <span class="dt">axis =</span> <span class="st">"y"</span>, </a>
<a class="sourceLine" id="cb17-11" title="11">         <span class="dt">gatingTemplate =</span> <span class="st">"Example-gatingTemplate.csv"</span>,</a>
<a class="sourceLine" id="cb17-12" title="12">         <span class="dt">contour_lines =</span> <span class="dv">15</span>,</a>
<a class="sourceLine" id="cb17-13" title="13">         <span class="dt">overlay =</span> CD8)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-30-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="visualise-gating-scheme-using-cyto_plot_gating_scheme" class="section level2">
<h2 class="hasAnchor">
<a href="#visualise-gating-scheme-using-cyto_plot_gating_scheme" class="anchor"></a>10. Visualise Gating Scheme Using <code>cyto_plot_gating_scheme</code>
</h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="co"># Back-gating and gate tracking</span></a>
<a class="sourceLine" id="cb18-2" title="2"><span class="kw"><a href="../reference/cyto_plot_gating_scheme.html">cyto_plot_gating_scheme</a></span>(gs[[<span class="dv">4</span>]], <span class="dt">back_gate =</span> <span class="ot">TRUE</span>, <span class="dt">gate_track =</span> <span class="ot">TRUE</span>, <span class="dt">legend =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-31-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
<div id="apply-saved-gates-to-samples-future-analyses" class="section level2">
<h2 class="hasAnchor">
<a href="#apply-saved-gates-to-samples-future-analyses" class="anchor"></a>11. Apply Saved Gates to Samples (Future Analyses)</h2>
<p>Since all the drawn gates have been saved to the gatingTemplate, next time you visit the data there is no need to re-draw gates! Simply apply the existing gatingTemplate to the data and you are right where you left off!</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="co"># Add samples to GatingSet</span></a>
<a class="sourceLine" id="cb19-2" title="2">gs &lt;-<span class="st"> </span><span class="kw">GatingSet</span>(fs)</a>
<a class="sourceLine" id="cb19-3" title="3"></a>
<a class="sourceLine" id="cb19-4" title="4"><span class="co"># Apply compensation</span></a>
<a class="sourceLine" id="cb19-5" title="5">gs &lt;-<span class="st"> </span><span class="kw">compensate</span>(gs, spill)</a>
<a class="sourceLine" id="cb19-6" title="6"></a>
<a class="sourceLine" id="cb19-7" title="7"><span class="co"># Transform fluorescent channels</span></a>
<a class="sourceLine" id="cb19-8" title="8">gs &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/transform">transform</a></span>(gs, trans)</a>
<a class="sourceLine" id="cb19-9" title="9"></a>
<a class="sourceLine" id="cb19-10" title="10"><span class="co"># Apply saved gates to GatingSet</span></a>
<a class="sourceLine" id="cb19-11" title="11">gt &lt;-<span class="st"> </span><span class="kw">gatingTemplate</span>(<span class="st">"Example-gatingTemplate.csv"</span>)</a>
<a class="sourceLine" id="cb19-12" title="12"><span class="kw">gating</span>(gt, gs)</a>
<a class="sourceLine" id="cb19-13" title="13"></a>
<a class="sourceLine" id="cb19-14" title="14"><span class="co"># Check gates have been applied</span></a>
<a class="sourceLine" id="cb19-15" title="15"><span class="kw">getNodes</span>(gs)</a></code></pre></div>
<pre><code>#&gt;  [1] "root"                                                                
#&gt;  [2] "/Cells"                                                              
#&gt;  [3] "/Cells/Single Cells"                                                 
#&gt;  [4] "/Cells/Single Cells/Live Cells"                                      
#&gt;  [5] "/Cells/Single Cells/Live Cells/Dendritic Cells"                      
#&gt;  [6] "/Cells/Single Cells/Live Cells/T Cells"                              
#&gt;  [7] "/Cells/Single Cells/Live Cells/T Cells/CD8 T Cells"                  
#&gt;  [8] "/Cells/Single Cells/Live Cells/T Cells/CD8 T Cells/CD69+ CD8 T Cells"
#&gt;  [9] "/Cells/Single Cells/Live Cells/T Cells/CD4 T Cells"                  
#&gt; [10] "/Cells/Single Cells/Live Cells/T Cells/CD4 T Cells/CD69+ CD4 T Cells"</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="co"># Plot gating strategy using cyto_plot_gating_scheme</span></a>
<a class="sourceLine" id="cb21-2" title="2"><span class="kw"><a href="../reference/cyto_plot_gating_scheme.html">cyto_plot_gating_scheme</a></span>(gs[[<span class="dv">1</span>]])</a></code></pre></div>
<p><img src="CytoRSuite_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="more-details" class="section level1">
<h1 class="hasAnchor">
<a href="#more-details" class="anchor"></a>More Details</h1>
<p>See vignettes for more in depth demonstration of package features.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li>
<a href="#overview">Overview</a><ul class="nav nav-pills nav-stacked">
<li><a href="#load-required-packages">1. Load Required Packages</a></li>
      <li><a href="#explore-activation-dataset">2. Explore Activation Dataset</a></li>
      <li><a href="#annotate-flowset-with-markers">3. Annotate flowSet with Markers</a></li>
      <li><a href="#annotate-flowset-with-experimental-details">4. Annotate flowSet with Experimental Details</a></li>
      <li><a href="#add-samples-to-gatingset-for-gating">5. Add Samples to GatingSet for Gating</a></li>
      <li><a href="#apply-compensation">6. Apply Compensation</a></li>
      <li><a href="#transform-fluorescent-channels">7. Transform Fluorescent Channels</a></li>
      <li><a href="#visualise-gatingset-using-cyto_plot">8. Visualise GatingSet using <code>cyto_plot</code></a></li>
      <li><a href="#draw-gates-using-gate_draw-to-complete-the-gating-scheme">9. Draw Gates Using <code>gate_draw</code> to Complete the Gating Scheme</a></li>
      <li><a href="#visualise-gating-scheme-using-cyto_plot_gating_scheme">10. Visualise Gating Scheme Using <code>cyto_plot_gating_scheme</code></a></li>
      <li><a href="#apply-saved-gates-to-samples-future-analyses">11. Apply Saved Gates to Samples (Future Analyses)</a></li>
      </ul>
</li>
      <li><a href="#more-details">More Details</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Dillon Hammill.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.9000.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
