# Internal function definitions for cyto_plot ----------------------------------

# These functions inherit all of cyto_plot arguments as a named list. Whether a
# 1D or 2D method is called is determined by cyto_plot based on the number of
# supplied channels.

#' cyto_plot_1d - 1D density distributions
#' 
#' @author Dillon Hammill, \email{Dillon.Hammill@anu.edu.au}
#'
#' @noRd
.cyto_plot_1d <- function(...){
  UseMethod(".cyto_plot_1d")
}

#' cyto_plot_1d - flowFrame Method
#'
#' Visualise 1-D flow cytometry density distributions for a flowFrame.
#'
#' @param x object of class \code{\link[flowCore:flowFrame-class]{flowFrame}}.
#' @param channel name of the channel or marker to be used to construct the
#'   plot.
#' @param axes_trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transformation object will be used internally to ensure that the axes
#'   labels of the plot are appropriately transformed. The transformation object
#'   will NOT be applied to the flowFrame internally and should be applied to
#'   the flowFrame prior to plotting.
#' @param overlay a \code{flowFrame}, \code{flowSet} or list of
#'   \code{flowFrames} to be overlaid onto the plot.
#' @param gate gate object(s) to be added to plot.  For \code{cyto_plot_1d} only
#'   gate objects of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}} in either 1 or 2
#'   dimensions are supported. Mulitple gates can be supplied either as a
#'   \code{list} or \code{\link[flowCore:filters-class]{filters}} object.
#' @param limits indicates whether the axes limits should be based on the
#'   \code{"data"} or \code{"machine"}, set to "machine" by default to show
#'   complete axes ranges. This argument will only alter the upper axis limits,
#'   to modify the lower limits use \code{xlim} and \code{ylim}.
#' @param popup logical indicating whether the plot should be constructed in a
#'   pop-up window, set to FALSE by default. \code{popup} will open OS-specific
#'   graphic device prior to plotting. Mac users will need to install
#'   \href{https://www.xquartz.org/}{XQuartz} for this functionality.
#' @param xlim lower and upper limits of x axis (e.g. c(0,5)).
#' @param ylim lower and upper limits of y axis (e.g. c(0,5)).
#' @param title title to use for the plot, set to the name of the sample by
#'   default. Title can be removed by setting this argument to \code{NA}.
#' @param xlab x axis label.
#' @param ylab y axis label.
#' @param density_modal logical indicating whether density should be normalised
#'   to mode and presented as a percentage. Set to \code{TRUE} by default.
#' @param density_smooth smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density.
#' @param density_stack numeric [0,1] indicating the degree of offset for
#'   overlaid populations, set to 0.5 by default.
#' @param density_fill colour(s) used to fill polygons.
#' @param density_fill_alpha numeric [0,1] used to control fill transparency,
#'   set to 1 by default to remove transparency.
#' @param density_line_type line type(s) to use for border(s), set to solid
#'   lines by default.
#' @param density_line_width line width for border.
#' @param density_line_col colour(s) for border line, set to "black" by default.
#' @param axes_text_font numeric indicating the font to use for axes, set to 1
#'   for plain font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param axes_text_size character expansion for axis text.
#' @param axes_text_col colour of axis text.
#' @param axes_label_text_font numeric indicating the font to use for title, set
#'   to 1 for plain font by default. See \code{\link[graphics:par]{?par}} font
#'   for details.
#' @param axes_label_text_size character expansion for axis labels.
#' @param axes_label_text_col colour of axis labels.
#' @param title_text_font numeric indicating the font to use for title, set to 2
#'   for bold font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param title_text_size character expansion for plot title.
#' @param title_text_col colour for plot title.
#' @param legend can be either \code{"line"} or \code{"fill"} to indicate
#'   whether a legend should be constructed based on the density \code{"line"}
#'   or \code{"fill"}, set to FALSE by default to remove the legend.
#' @param legend_text vector of labels to use for the legend.
#' @param legend_text_font numeric indicating the font to use for labels, set to
#'   1 for plain font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param legend_text_size character expansion for legend text, set to 1 by
#'   default.
#' @param legend_text_col colour of text used in legend, set to \code{"black"}
#'   by default.
#' @param legend_line_col vector of line colours to use for legend.
#' @param legend_box_fill vector of fill colours to use for legend.
#' @param gate_line_type integer [0,6] which controls the line type, set to
#'   \code{1} to draw solid lines by default.
#' @param gate_line_width numeric to adjust line thickness of gates, set to
#'   \code{2.5} by default.
#' @param gate_line_col indicates the colour of the gate to be constructed, set
#'   to \code{"red"} by default.
#' @param label logical indicating whether gated populations should be labelled.
#'   If the names of the populations are supplied as the text.labels argument,
#'   the population name and frequency will be included in the labels, otherwise
#'   only the population frequencies will be included in the labels.
#' @param label_text vector of population names to use in labels. Set to NA to
#'   exclude population names.
#' @param label_stat indicates the type of statistic to include in the label,
#'   can be \code{"percent"}, \code{"count"}, \code{"mean"}, \code{"median"},
#'   \code{"mode"} or \code{"geo mean"}, set to \code{"percent"} for gated data
#'   or \code{NA} to exclude statistics for un-gated data.
#' @param label_text_font numeric indicating the font to use for labels, set to
#'   2 for bold font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param label_text_size character expansion for label text, set to 0.8 by
#'   default.
#' @param label_text_col colour of text used in labels, set to \code{"black"} by
#'   default.
#' @param label_box_x x co-ordinate to manually adjust the position of the label
#'   on the plot.
#' @param label_box_y y co-ordinate(s) to manually adjust the position of the
#'   label(s) on the plot.
#' @param label_box_alpha numeric controlling backgropund fill transparency of
#'   label boxes, set to 0.6 by default to introduce some transparency.
#' @param border_line_type line type to use for plot border, set to 1 by default
#'   for a sold border.
#' @param border_line_width line width for plot border, set to 1 by default.
#' @param border_line_col line colour for plot border, set to "black" by
#'   default.
#' @param ... additional arguments passed to \code{\link[graphics:plot]{plot}}.
#'
#' @examples
#' \dontrun{
#' library(CytoRSuiteData)
#' fs <- Activation
#' 
#' cyto_plot_1d(fs[[1]],
#'   channel = "FSC-A",
#'   overlay = fs[[2]],
#'   density_fill = c("red", "blue")
#' )
#' }
#' 
#' @importFrom flowCore exprs parameters identifier
#' @importFrom flowWorkspace pData
#' @importFrom graphics plot axis title abline polygon legend par box
#' @importFrom grDevices adjustcolor
#' @importFrom stats density
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @noRd
setMethod(.cyto_plot_1d,
          signature = "flowFrame",
          definition = function(x,
                                channel = NULL,
                                axes_trans = NULL,
                                overlay = NULL,
                                gate = NA,
                                limits = "machine",
                                popup = FALSE,
                                xlim = NULL,
                                ylim = NULL,
                                title,
                                xlab = NA,
                                ylab = NA,
                                density_modal = TRUE,
                                density_smooth = 1.5,
                                density_stack = 0.5,
                                density_fill,
                                density_fill_alpha = 1,
                                density_line_type = 1,
                                density_line_width = 1,
                                density_line_col = "black",
                                axes_text_font = 1,
                                axes_text_size = 1,
                                axes_text_col = "black",
                                axes_label_text_font = 1,
                                axes_label_text_size = 1.1,
                                axes_label_text_col = "black",
                                title_text_font = 2,
                                title_text_size = 1.1,
                                title_text_col = "black",
                                legend = FALSE,
                                legend_text,
                                legend_text_font = 1,
                                legend_text_size = 1,
                                legend_text_col = "black",
                                legend_line_col = NA,
                                legend_box_fill = NA,
                                gate_line_type = 1,
                                gate_line_width = 2.5,
                                gate_line_col = "red",
                                label = TRUE,
                                label_text = NA,
                                label_stat = "percent",
                                label_text_font = 2,
                                label_text_size = 1,
                                label_text_col = "black",
                                label_box_x = NA,
                                label_box_y = NA,
                                label_box_alpha = 0.6,
                                border_line_type = 1,
                                border_line_width = 1,
                                border_line_col = "black", ...) {
            
            # Prevent scientific notation on axes
            options(scipen = 999)
            
            # Assign x to fr
            fr <- x
            
            # Return channel name if marker supplied
            channel <- cyto_channel_check(fr,
                                          channels = channel,
                                          plot = TRUE
            )
            
            # Get transformList object
            if (!is.null(axes_trans)) {
              axes_trans <- cyto_trans_check(axes_trans,
                                             inverse = FALSE
              )
            }
            
            # Get X Axis Breaks and Labels from trans if supplied
            xtext <- .cyto_axes_text(
              x = fr,
              channels = channel,
              trans = axes_trans
            )[[1]]
            
            # Check overlay return list of fowFrames
            if (!is.null(overlay)) {
              overlay <- .cyto_overlay_check(
                x = fr,
                overlay = overlay
              )
              
              # title missing - no title for plots with overlay
              if (missing(title)) {
                title <- NA
              }
              
              if (!density_modal) {
                message("Overlays must be normalised to mode.")
                density_modal <- TRUE
              }
            }
            
            # number of overlays
            ovn <- length(overlay)
            
            # number of layers
            lyrs <- ovn + 1
            
            # group_by fr with overlay if supplied - named list of fr & overlay
            if (!is.null(overlay)) {
              frs <- c(list(fr), overlay)
              names(frs) <- unlist(
                lapply(frs, function(fr) {
                  identifier(fr)
                })
              )
            } else {
              frs <- list(fr)
              names(frs) <- identifier(fr)
            }
            
            # Extract information
            fr.data <- pData(parameters(fr))
            fr.channels <- BiocGenerics::colnames(fr)
            
            # Extract data from frs and calculate kernel density
            frs.dens <- .cyto_density(
              x = frs,
              channel = channel,
              adjust = density_smooth,
              modal = density_modal,
              density_stack = density_stack
            )
            
            # Y axis labels
            if (ovn == 0) {
              ytext <- TRUE
            } else if (ovn != 0) {
              if (density_stack == 0) {
                ytext <- TRUE
              } else {
                ytext <- FALSE
              }
            }
            
            # Get y axis values for horizontal lines
            if (density_stack == 0) {
              ofst <- 0
            } else {
              ofst <- seq(
                0,
                ovn * density_stack * 100,
                density_stack * 100
              )
            }
            
            # Title missing - set to sample name
            if (missing(title)) {
              
              title <- identifier(fr)
              
              if(title == "anonymous"){
                title <- "All Events"
              }
              
            }
            
            # Y Axis Title
            if (is.na(ylab)) {
              if (density_modal) {
                ylab <- "Density Normalised to Mode (%)"
              } else {
                ylab <- "Density"
              }
            }
            
            # X Axis Title
            if (is.na(xlab)) {
              if (!is.na(fr.data$desc[which(fr.channels == channel)])) {
                xlab <- paste(fr.data$desc[which(fr.channels == channel)],
                              channel,
                              sep = " "
                )
              } else if (is.na(fr.data$desc[which(fr.channels == channel)])) {
                xlab <- paste(channel, sep = " ")
              }
            }
            
            # Y Axis Limits
            if (is.null(ylim)) {
              if (is.null(overlay)) {
                if (!density_modal) {
                  ylim <- range(frs.dens[[1]]$y)
                } else if (density_modal) {
                  ylim <- c(0, 100)
                }
              } else if (!is.null(overlay)) {
                # No offset with overlay y limits c(0,100)
                if (density_stack == 0) {
                  ylim <- c(0, 100)
                } else if (density_stack != 0) {
                  # Overlays with offset
                  ylim <- c(0, (100 + ovn * density_stack * 100))
                }
              }
            }
            
            # X Axis limits
            if (is.null(xlim)) {
              xlim <- suppressWarnings(.cyto_plot_limits(
                x = fr,
                channels = channel,
                overlay = overlay,
                limits = limits
              )[[1]])
            }
            
            # Overlay colours
            cols <- colorRampPalette(c(
              "grey",
              "bisque4",
              "brown1",
              "red",
              "darkred",
              "chocolate",
              "orange",
              "yellow",
              "yellowgreen",
              "green",
              "aquamarine",
              "cyan",
              "cornflowerblue",
              "blue",
              "blueviolet",
              "purple",
              "magenta",
              "deeppink"
            ))
            
            # Density fill
            if (missing(density_fill)) {
              density_fill <- NA
            }
            
            # Get density_fill for each layer
            if (all(is.na(density_fill))) {
              density_fill <- cols(length(frs.dens))
            } else if (length(density_fill) < length(frs.dens)) {
              density_fill <- c(
                density_fill,
                cols((length(frs.dens) - length(density_fill)))
              )
            } else if (length(density_fill) > length(frs.dens)) {
              density_fill <- density_fill[length(frs.dens)]
            }
            
            # Legend text
            if (missing(legend_text)) {
              legend_text <- names(frs)
            }
            
            # Number of supported gates
            gates <- .cyto_gate_count(gate)
            
            # Get named list of arguments
            args <- as.list(environment())
            
            # Split arguments
            args <- .arg_split(
              x = args[-c(match(
                c(
                  "x",
                  "fr",
                  "channel",
                  "axes_trans",
                  "overlay",
                  "gates",
                  "xlim",
                  "ylim",
                  "popup",
                  "limits",
                  "gate",
                  "cols",
                  "ofst",
                  "ytext",
                  "xtext",
                  "frs.dens",
                  "fr.channels",
                  "fr.data",
                  "frs",
                  "lyrs",
                  "ovn"
                ),
                names(args)
              ))],
              channels = channel,
              n = lyrs,
              plots = 1,
              layers = lyrs,
              gates = gates
            )
            
            # Unlist arguments for single plot
            args <- lapply(args, function(x) x[[1]])
            
            # Pop-up
            if (popup == TRUE) {
              .cyto_plot_window()
            }
            
            # Plot margins
            .cyto_plot_margins(
              x = fr,
              overlay = overlay,
              legend = args[["legend"]],
              legend_text = args[["legend_text"]],
              title = args[["title"]]
            )
            
            # Set up empty plot
            if (is.null(xtext) & ytext == FALSE) {
              graphics::plot(1,
                             type = "n",
                             yaxt = "n",
                             xlim = xlim,
                             ylim = ylim,
                             axes = TRUE,
                             font.axis = args[["axes_text_font"]],
                             cex.axis = args[["axes_text_size"]],
                             col.axis = args[["axes_text_col"]],
                             ann = FALSE,
                             bty = "n", ...
              )
              box(
                which = "plot",
                lty = args[["border_line_type"]],
                lwd = args[["border_line_width"]],
                col = args[["border_line_col"]]
              )
              abline(
                h = ofst,
                col = args[["density_line_col"]],
                lwd = args[["density_line_width"]],
                lty = args[["density_line_type"]]
              )
              
              if (!is.na(args[["title"]])) {
                title(
                  main = args[["title"]],
                  cex.main = args[["title_text_size"]],
                  col.main = args[["title_text_col"]],
                  font.main = args[["title_text_font"]]
                )
              }
              
              title(
                xlab = args[["xlab"]],
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
              title(
                ylab = args[["ylab"]],
                mgp = c(2, 0, 0),
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
            } else if (is.null(xtext) & ytext == TRUE) {
              graphics::plot(1,
                             type = "n",
                             xlim = xlim,
                             ylim = ylim,
                             axes = TRUE,
                             font.axis = args[["axes_text_font"]],
                             cex.axis = args[["axes_text_size"]],
                             col.axis = args[["axes_text_col"]],
                             ann = FALSE,
                             las = 1,
                             bty = "n", ...
              )
              box(
                which = "plot",
                lty = args[["border_line_type"]],
                lwd = args[["border_line_width"]],
                col = args[["border_line_col"]]
              )
              abline(
                h = ofst,
                col = args[["density_line_col"]],
                lwd = args[["density_line_width"]],
                lty = args[["density_line_type"]]
              )
              
              if (!is.na(args[["title"]])) {
                title(
                  main = args[["title"]],
                  cex.main = args[["title_text_size"]],
                  col.main = args[["title_text_col"]],
                  font.main = args[["title_text_font"]]
                )
              }
              
              title(
                xlab = args[["xlab"]],
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
              title(
                ylab = args[["ylab"]],
                mgp = c(3, 0, 0),
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
            } else if (!is.null(xtext) & ytext == FALSE) {
              graphics::plot(1,
                             type = "n",
                             yaxt = "n",
                             xaxt = "n",
                             xlim = xlim,
                             ylim = ylim,
                             axes = TRUE,
                             cex.axis = args[["axes_text_size"]],
                             col.axis = args[["axes_text_col"]],
                             ann = FALSE,
                             bty = "n", ...
              )
              axis(1,
                   at = xtext$at,
                   labels = xtext$label,
                   font = args[["axes_text_font"]],
                   cex.axis = args[["axes_text_size"]],
                   col.axis = args[["axes_text_col"]]
              )
              box(
                which = "plot",
                lty = args[["border_line_type"]],
                lwd = args[["border_line_width"]],
                col = args[["border_line_col"]]
              )
              abline(
                h = ofst,
                col = args[["density_line_col"]],
                lwd = args[["density_line_width"]],
                lty = args[["density_line_type"]]
              )
              
              if (!is.na(args[["title"]])) {
                title(
                  main = args[["title"]],
                  cex.main = args[["title_text_size"]],
                  col.main = args[["title_text_col"]],
                  font.main = args[["title_text_font"]]
                )
              }
              
              title(
                xlab = args[["xlab"]],
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
              title(
                ylab = args[["ylab"]],
                mgp = c(2, 0, 0),
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
            } else if (!is.null(xtext) & ytext == TRUE) {
              graphics::plot(1,
                             type = "n",
                             xaxt = "n",
                             xlim = xlim,
                             ylim = ylim,
                             axes = TRUE,
                             xlab = xlab,
                             ylab = ylab,
                             cex.axis = args[["axes_text_size"]],
                             col.axis = args[["axes_text_col"]],
                             ann = FALSE,
                             las = 1,
                             bty = "n", ...
              )
              axis(1,
                   at = xtext$at,
                   labels = xtext$label,
                   font = args[["axes_text_font"]],
                   cex.axis = args[["axes_text_size"]],
                   col.axis = args[["axes_text_col"]]
              )
              box(
                which = "plot",
                lty = args[["border_line_type"]],
                lwd = args[["border_line_width"]],
                col = args[["border_line_col"]]
              )
              abline(
                h = ofst,
                col = args[["density_line_col"]],
                lwd = args[["density_line_width"]],
                lty = args[["density_line_type"]]
              )
              
              if (!is.na(args[["title"]])) {
                title(
                  main = args[["title"]],
                  cex.main = args[["title_text_size"]],
                  col.main = args[["title_text_col"]],
                  font.main = args[["title_text_font"]]
                )
              }
              
              title(
                xlab = args[["xlab"]],
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
              title(
                ylab = args[["ylab"]],
                mgp = c(3, 0, 0),
                font.lab = args[["axes_label_text_font"]],
                col.lab = args[["axes_label_text_col"]],
                cex.lab = args[["axes_label_text_size"]]
              )
            }
            
            # Add density distributions - reverse plot order and colours
            if (!is.null(overlay) & args[["density_stack"]] == 0) {
              mapply(
                function(fr.dens,
                         density_fill,
                         density_line_col,
                         density_line_width,
                         density_line_type,
                         density_fill_alpha) {
                  polygon(fr.dens,
                          col = adjustcolor(density_fill, density_fill_alpha),
                          border = density_line_col,
                          lwd = density_line_width,
                          lty = density_line_type
                  )
                }, frs.dens,
                args[["density_fill"]],
                args[["density_line_col"]],
                args[["density_line_width"]],
                args[["density_line_type"]],
                args[["density_fill_alpha"]]
              )
            } else {
              mapply(
                function(fr.dens,
                         density_fill,
                         density_line_col,
                         density_line_width,
                         density_line_type,
                         density_fill_alpha) {
                  polygon(fr.dens,
                          col = adjustcolor(density_fill, density_fill_alpha),
                          border = density_line_col,
                          lwd = density_line_width,
                          lty = density_line_type
                  )
                }, rev(frs.dens),
                rev(args[["density_fill"]]),
                rev(args[["density_line_col"]]),
                rev(args[["density_line_width"]]),
                rev(args[["density_line_type"]]),
                rev(args[["density_fill_alpha"]])
              )
            }
            
            # Add legend
            if (!is.null(overlay) & args[["legend"]]) {
              
              # Legend TRUE default to fill
              if (args[["legend"]]) {
                args[["legend"]] <- "fill"
              }
              
              # Legend position x
              legend.x <- par("usr")[2] + 0.025 * par("usr")[2]
              
              # Legend position y
              legend.y <- mean(par("usr")[c(3, 4)])
              legend.y <- legend.y + (((par("usr")[4]) / 21) * 0.5 * length(frs.dens))
              
              # Legend labels
              legend_text <- rev(args[["legend_text"]])
              
              # Line legend
              if (args[["legend"]] == "line") {
                
                # No line colours supplied - use density_line_col
                if (all(is.na(args[["legend_line_col"]]))) {
                  args[["legend_line_col"]] <- args[["density_line_col"]]
                }
                legend(
                  x = legend.x,
                  y = legend.y,
                  legend = legend_text,
                  col = rev(args[["legend_line_col"]]),
                  lty = rev(args[["density_line_type"]]),
                  lwd = rev(args[["density_line_width"]]),
                  xpd = TRUE,
                  bty = "n",
                  x.intersp = 0.5,
                  cex = args[["legend_text_size"]],
                  text.col = rev(args[["legend_text_col"]]),
                  text.font = rev(args[["legend_text_font"]])
                )
                
                # Fill legend
              } else if (args[["legend"]] == "fill") {
                
                # No fill colours supplied - use density_line_col
                if (all(is.na(args[["legend_box_fill"]]))) {
                  args[["legend_box_fill"]] <- args[["density_fill"]]
                }
                
                # Alpha adjust legend_fill
                if (!all(args[["density_fill_alpha"]] == 1)) {
                  args[["legend_box_fill"]] <- mapply(
                    function(legend_box_fill,
                             density_fill_alpha) {
                      adjustcolor(legend_box_fill, density_fill_alpha)
                    }, args[["legend_box_fill"]],
                    args[["density_fill_alpha"]]
                  )
                }
                
                legend(
                  x = legend.x,
                  y = legend.y,
                  legend = legend_text,
                  fill = rev(args[["legend_box_fill"]]),
                  xpd = TRUE,
                  bty = "n",
                  x.intersp = 0.5,
                  cex = args[["legend_text_size"]],
                  text.col = rev(args[["legend_text_col"]]),
                  text.font = rev(args[["legend_text_font"]])
                )
              }
            }
            
            # Gates - no overlay
            if (gates != 0 & is.null(overlay)) {
              gate <- cyto_plot_gate(gate,
                                     channels = channel,
                                     gate_line_col = args[["gate_line_col"]],
                                     gate_line_width = args[["gate_line_width"]],
                                     gate_line_type = args[["gate_line_type"]]
              )
              
              # Labels
              if (args[["label"]]) {
                
                # Population names missing - show percantage only
                suppressMessages(cyto_plot_label(
                  x = fr,
                  channels = channel,
                  gates = gate,
                  trans = axes_trans,
                  text = args[["label_text"]],
                  stat = args[["label_stat"]],
                  text_size = args[["label_text_size"]],
                  text_font = args[["label_text_font"]],
                  text_col = args[["label_text_col"]],
                  box_alpha = args[["label_box_alpha"]]
                ))
              }
            } else if (gates != 0 & 
                       !is.null(overlay) & 
                       args[["density_stack"]] != 0) {
              .cyto_overlay_gate(
                x = fr,
                channel = channel,
                trans = axes_trans,
                overlay = overlay,
                gates = gate,
                density_stack = args[["density_stack"]],
                label_text = args[["label_text"]],
                label_stat = args[["label_stat"]],
                label_text_size = args[["label_text_size"]],
                label_text_font = args[["label_text_font"]],
                label_text_col = args[["label_text_col"]],
                label_box_x = args[["label_box_x"]],
                label_box_y = args[["label_box_y"]],
                label_box_alpha = args[["label_box_alpha"]],
                gate_line_col = args[["gate_line_col"]],
                gate_line_width = args[["gate_line_width"]],
                gate_line_type = args[["gate_line_type"]]
              )
            } else if (gates != 0 & 
                       !is.null(overlay) & 
                       args[["density_stack"]] == 0) {
              message("Gating overlays without stacking is not supported.")
            }
            
            # No gates - labels
            if (gates == 0 & 
                !all(is.na(args[["label_text"]])) & 
                args[["label"]]) {
              if (is.null(overlay)) {
                
                # label # limited to # layers - arg_split
                mapply(
                  function(label_text,
                           label_stat,
                           label_text_size,
                           label_text_font,
                           label_text_col,
                           label_box_x,
                           label_box_y,
                           label_box_alpha) {
                    if (label_stat == "percent") {
                      label_stat <- NA
                    }
                    suppressMessages(cyto_plot_label(
                      x = fr,
                      channels = channel,
                      gates = gate, trans = axes_trans,
                      text = label_text,
                      stat = label_stat,
                      text_x = label_box_x,
                      text_y = label_box_y,
                      text_size = label_text_size,
                      text_font = label_text_font,
                      text_col = label_text_col,
                      box_alpha = label_box_alpha
                    ))
                  }, args[["label_text"]],
                  args[["label_stat"]],
                  args[["label_text_size"]],
                  args[["label_text_font"]],
                  args[["label_text_col"]],
                  args[["label_box_x"]],
                  args[["label_box_y"]],
                  args[["label_box_alpha"]]
                )
              } else if (gates == 0 & !is.null(overlay)) {
                fr.lst <- c(list(fr), overlay)
                
                # Number of labels must equal number of layers
                if (length(args[["label_text"]]) != length(fr.lst)) {
                  message("cyto_plot expects one label per layer.")
                  
                  if (all(is.na(args[["label_box_y"]]))) {
                    args[["label_box_y"]] <- unlist(
                      lapply(seq_along(fr.lst), function(x) {
                        stk <- args[["density_stack"]]
                        (0.5 * stk * 100) + ((x - 1) * stk * 100)
                      })
                    )
                  }
                  
                  mapply(
                    function(fr,
                             label_text,
                             label_stat,
                             label_text_size,
                             label_text_font,
                             label_text_col,
                             label_box_x,
                             label_box_y,
                             label_box_alpha) {
                      if (label_stat == "percent") {
                        label_stat <- NA
                      }
                      suppressMessages(cyto_plot_label(
                        x = fr,
                        channels = channel,
                        gates = gate,
                        trans = axes_trans,
                        text = label_text,
                        stat = label_stat,
                        text_x = label_box_x,
                        text_y = label_box_y,
                        text_size = label_text_size,
                        text_font = label_text_font,
                        text_col = label_text_col,
                        box_alpha = label_box_alpha
                      ))
                    }, fr.lst, args[["label_text"]],
                    args[["label_stat"]],
                    args[["label_text_size"]],
                    args[["label_text_font"]],
                    args[["label_text_col"]],
                    args[["label_box_x"]],
                    args[["label_box_y"]],
                    args[["label_box_alpha"]]
                  )
                }
              }
            }
            
            # Return options to default
            options(scipen = 0)
            
            # Return plot margins to default
            par(mar = c(5, 4, 4, 2) + 0.1)
          }
)