# Gates are used for calculation of statistics only
# Co-ordinates must be supplied/calculated else where

#' Add boxed text labels to cyto_plot
#'
#' Interactively label existing plots with boxed labels containing text and
#' statistics.
#'
#' @param x object of class \code{"flowFrame"}.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param gate object of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}},
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}},
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}, \code{"list"} or
#'   \code{\link[flowCore:filters-class]{filters}}.
#' @param text character string to include in the label above the statistic
#'   (e.g. population name(s)).
#' @param stat indicates the type of statistic to include in the label, can be
#'   either code{"count"}, \code{"median"}, \code{"mean"}, \code{"mode"},
#'   \code{"geo mean"} or \code{"CV"}. \code{stat} is set to \code{"median"} by
#'   default. Statistics for fluorescent intensity are calculated for the entire
#'   distribution. Only count and percent statistics are supported for 2D plots.
#' @param text_x vector containing the x co-ordinates for the plot labels. Label
#'   positions can be interactively selected if no co-ordinates are manually
#'   supplied.
#' @param text_y vector containing the x co-ordinates for the plot labels. Label
#'   positions can be interactively selected if no co-ordinates are manually
#'   supplied.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param fill fill colour to use for labels, set to "white" by default.
#' @param fill_alpha numeric [0,1] controls the transparency of the fill colour,
#'   set to \code{0.6} by default.
#' @param density_smooth smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density for mode
#'   calculation.
#'
#' @return add a boxed text label to an existing cyto_plot.
#'
#' @importFrom flowCore Subset
#'
#' @examples
#' library(CytoRSuiteData)
#'
#' # Load in samples
#' fs <- Activation
#' gs <- GatingSet(fs)
#'
#' # Apply compensation
#' gs <- compensate(gs, fs[[1]]@description$SPILL)
#'
#' # Transform fluorescent channels
#' trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(fs))
#' gs <- transform(gs, trans)
#'
#' # Gate using gate_draw
#' gating(Activation_gatingTemplate, gs)
#'
#' # Plot
#' cyto_plot(gs[[32]],
#'   parent = "CD4 T Cells",
#'   channels = c("CD69")
#' )
#'
#' # Label - median fluorescent intensity
#' cyto_plot_label2(getData(gs, "CD4 T Cells")[[32]],
#' channels = "CD69",
#' stat = "median",
#' text = "MedFI",
#' trans = trans,
#' text_x = 3,
#' text_y = 50
#' )
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @export
cyto_plot_label2 <- function(x,
                             channels,
                             gate = NA,
                             text = NA,
                             stat = NA,
                             text_x = NA,
                             text_y = NA,
                             trans = NA,
                             text_font = 2,
                             text_size = 0.8,
                             text_col = "black",
                             fill = "white",
                             fill_alpha = 0.6,
                             density_smooth = 0.6){
  
  # x must be a flowFrame
  if(!missing(x)){
    if(!inherits(x, "flowFrame")){
      stop("'x' must be a flowFrame object.")
    }
  }
  
  # Convert to valid statistic 
  if(!.all_na(stat)){
    stat <- unlist(lapply(stat, function(z) {.cyto_stat_check(z)}))
  }
  
  # Convert trans to transformList - required for stats calculation
  if(!.all_na(stat)){
    trans <- cyto_transform_convert(trans, inverse = FALSE)
  }
  
  # Check for statistics
  if(!.all_na(stat)){
    
    # Transformations are required for certain statistics
    if(stat %in% c("median",
                   "mode",
                   "mean",
                   "geo mean",
                   "CV")){
    
      if(.all_na(trans)){
        stop(
          paste("Supply transformList/transformerList to calculate", stat, ".")
        )
      }
    
    }
  
    # Only 'count' valid for 2D plots without gates
    if(length(channels) == 2 & .all_na(gate) & !all(stat == "count")){
      stop("Only 'count' is supported for 2D plots without gates.")
    }
  
    # Only count, freq and CV are supported in 2D plots
    if(length(channels) == 2 & !all(stat %in% c("count","freq","CV"))){
      stop("Only 'count', 'precent' and 'CV' are supported in 2D plots.")
    }
    
    # Freq only supported if gates supplied
    if(stat == "freq" & .all_na(gate)){
      stop("Supply gate objects to 'gate' to calculate frequency.")
    }
  }

  # Convert gate to list of gate objects
  if(!.all_na(gate)){
    if(!inherits(gate, "list")){
      if(inherits(gate, "rectangleGate") |
         inherits(gate, "polygonGate") |
         inherits(gate, "ellipsoidGate")){
        gate <- list(gate)
      }else if(inherits(gate, "filters")){
        gate <- unlist(gate)
      }
    }else{
      gate <- unlist(gate)
    }
  }
  
  # Gates supplied - pull out populations
  if(!.all_na(stat)){
    if(!.all_na(gate)){
      pops <- lapply(seq_len(length(gate)), function(z){
        Subset(x, gate[[z]])
      })
    }else{
      pops <- list(x)
    }
  }

  # Calculate statistics per gate
  if(!.all_na(stat)){
    
    st <- unlist(lapply(pops, function(z){
      
      if(stat == "freq"){
        sts <- .cyto_count(z)/.cyto_count(x)*100
        sts <- sprintf("%.2f %%", sts)
      }else{
        sts <- cyto_stats_compute(z,
                                 channels = channels,
                                 trans = trans,
                                 stat = stat,
                                 format = "long",
                                 density_smooth = density_smooth)
        sts <- round(sts[, ncol(sts)], 2)
      }
      return(sts)
      
    }))
    
  }else{
    st <- NA
  }
  
  # Add labels to plot
  invisible(mapply(function(text,
                            st,
                            text_x,
                            text_y,
                            text_font,
                            text_size,
                            text_col,
                            fill,
                            fill_alpha){
    
    # Co-ordinates can be interactively selected
    if(any(.all_na(c(text_x,text_y)))){
      message("Select a location on the plot the position the label.")
      text_xy <- locator(n = 1)
      text_x <- text_xy[[1]]
      text_y <- text_xy[[2]]
    }
    
    # Add labels to plot
    if(!.all_na(text) & !.all_na(stat)){
      .boxed.labels(
        x = text_x,
        y = text_y,
        labels = paste(text, st, sep = "\n"),
        border = FALSE,
        font = text_font,
        cex = text_size,
        col = text_col,
        bg = fill,
        alpha.bg = fill_alpha
      )
    }else if(!.all_na(text) & .all_na(stat)){
      .boxed.labels(
        x = text_x,
        y = text_y,
        labels = text,
        border = FALSE,
        font = text_font,
        cex = text_size,
        col = text_col,
        bg = fill,
        alpha.bg = fill_alpha
      )
    }else if(.all_na(text) & !.all_na(stat)){
      .boxed.labels(
        x = text_x,
        y = text_y,
        labels = st,
        border = FALSE,
        font = text_font,
        cex = text_size,
        col = text_col,
        bg = box_fill,
        alpha.bg = box_alpha
      )
    }
  
  },
  text, 
  st,
  text_x,
  text_y,
  text_font,
  text_size,
  text_col,
  fill,
  fill_alpha
  ))
  
}