## CYTO_SPILLOVER_COMPUTE ------------------------------------------------------

#' Compute Spillover Matrix
#'
#' \code{cyto_spillover_compute} automatically computes the fluorescent
#' spillover matrix for a set of single colour compensation controls using
#' either the method proposed by Bagwell et al. (1993) or the more recent method
#' proposed by Roca et al. (2021).
#'
#' The method proposed by Roca et al. (2021) is now the default method, and has
#' been implemented in \code{cyto_spillover_compute} as a fully automated
#' algorithm to compute the spillover matrix. Users simply need to ensure that
#' the channel associated with each control is annotated in the
#' \code{cyto_details()} of the supplied data or alternatively this information
#' can be interactively supplied through a channel match file using
#' \code{cyto_channel_match()}.
#'
#' The method proposed by Bagwell et al. (1993) is also supported but is
#' implemented as a semi-automated approach as it requires gating of the
#' positive and negative signal within each single colour control to accurately
#' compute the spillover coefficients. Gating is performed on a per channel
#' basis with the user manually drawing interval gates around the positive and
#' negative signal for each control. If a universal unstained control is
#' supplied, users are only asked to gate the positive signal for each control
#' and the unstained control will be used as the reference for the negative
#' signal in each channel.
#'
#' The computed spillover is returned as a matrix and exported as a csv file
#' specified by the \code{save_as} argument. To assess the quality of the
#' compensation, refer to \code{\link{cyto_spillover_edit}} and
#' \code{\link{cyto_plot_compensation}}. Users can apply their computed
#' spillover matrices to their samples using \code{\link{cyto_compensate}}.
#'
#' @param x object of class \code{\link[flowCore:flowSet-class]{flowSet}} or
#'   \code{\link[flowWorkspace:GatingSet-class]{GatingSet}} containing
#'   transformed and gated compensation controls.
#' @param parent name of the population to use for the spillover calculation
#'   when a GatingSet object is supplied, set to the last node of the GatingSet
#'   by default (e.g. "Single Cells"). For greater flexibility, users can
#'   specify a parent population for each control, which will be extracted for
#'   the spillover calculation (e.g. Lymphocytes for CD4 APC or Myeloid Cells
#'   for CD11b FITC). The parent populations for each control can also be
#'   specified in a \code{parent} column in the channel match CSV file or in
#'   \code{cyto_details}.
#' @param axes_trans object of class
#'   \code{\link[flowWorkspace:transformerList]{transformerList}} generated by a
#'   \code{cyto_transformer} which contains the transformer definitions used to
#'   transform the data. Transformer definitions are only required when a
#'   flowSet object is supplied.
#' @param channel_match name of csv file to associate a fluorescent channel with
#'   each of the compensation controls. The \code{channel_match} file should
#'   contain a "name" column with the names of the compensation controls and a
#'   "channel" column to associate a fluorescent channel with each compensation
#'   control. Users need not generate this file by hand as it will be created
#'   following the channel selection process. This information can also be added
#'   directly to the samples using \code{cyto_details_edit}.
#' @param save_as name of a csv file to which the computed spillover matrix
#'   should be written, set to \code{Spillover-Matrix.csv} prefixed with the
#'   date by default.
#' @param type options include \code{"Bagwell"} or \code{"Roca"} to indicate
#'   which method to use when computing the spillover matrix, set to
#'   \code{"Roca"} by default. Refer to \code{references} section for more
#'   details about each method.
#' @param axes_limits options include \code{"auto"}, \code{"data"} or
#'   \code{"machine"} to use optimised, data or machine limits respectively. Set
#'   to \code{"machine"} by default to use entire axes ranges. Fine control over
#'   axes limits can be obtained by altering the \code{xlim} and \code{ylim}
#'   arguments.
#' @param ... additional arguments passed to \code{\link{cyto_plot}}.
#'
#' @return spillover matrix and write spillover matrix to csv file named in
#'   accordance with \code{spillover}.
#'
#' @examples
#' \dontrun{
#' library(CytoExploreRData)
#'
#' # Bypass directory check for external files
#' options("CytoExploreR_wd_check" = FALSE)
#'
#' # Load in compensation controls
#' fs <- Compensation
#' gs <- GatingSet(Compensation)
#'
#' # Gate using cyto_gate_draw
#' gt <- Compensation_gatingTemplate
#' cyto_gatingTemplate_apply(gs, gt)
#'
#' # Channel match fille
#' cmfile <- system.file("extdata",
#'   "Compensation-Channels.csv",
#'   package = "CytoExploreRData"
#' )
#'
#' # Compute fluorescent spillover matrix
#' spill <- cyto_spillover_compute(cyto_extract(gs, "Single Cells"),
#'   channel_match = cmfile,
#'   spillover = "Example-spillover.csv"
#' )
#'
#' # Compensate samples
#' gs <- cyto_compensate(gs, spill)
#'
#' # Return CytoExploreR_wd_check to default
#' options("CytoExploreR_wd_check" = TRUE)
#' }
#'
#' @seealso \code{\link{cyto_spillover_edit}}
#' @seealso \code{\link{cyto_spillover_edit}}
#' @seealso \code{\link{cyto_plot_compensation}}
#' @seealso \code{\link{cyto_compensate}}
#'
#' @author Dillon Hammill, \email{Dillon.Hammill@anu.edu.au}
#'
#' @references C. B. Bagwell & E. G. Adams (1993). Fluorescence spectral overlap
#'   compensation for any number of flow cytometry parameters. in: Annals of the
#'   New York Academy of Sciences, 677:167-184.
#'
#' @references Roca et al. (2021). AutoSpill is a principled framework that
#'   simplifies the analysis of multichromatic flow cytometry data. Nature
#'   Communications 12(2890).
#'
#' @export
cyto_spillover_compute <- function(x,
                                   parent = "root",
                                   axes_trans = NA,
                                   channel_match = NULL,
                                   spillover = NULL,
                                   save_as = NULL,
                                   type = "roca",
                                   axes_limits = "machine",
                                   ...) {
  

  
  # PREPARE DATA ---------------------------------------------------------------
  
  # TRANSFORMATIONS
  if(!.all_na(axes_trans)) {
    axes_trans <- cyto_transformers_extract(x)
  }
  
  # COPY DATA
  x <- cyto_copy(x)
  
  # BAGWELL METHOD REQUIRES TRANSFORMED DATA
  if(grepl("^b", type, ignore.case = TRUE)) {
    if(.all_na(axes_trans)) {
      axes_trans <- cyto_transformers_define(x, 
                                             type = "biex",
                                             plot = FALSE)
      suppressWarnings(cyto_transform(x,
                                      trans = axes_trans,
                                      plot = FALSE,
                                      quiet = TRUE))
    }
  }
  
  # REMOVE EXCESS CONTRTOLS, ANNOTATE CHANNELS & COPY DATA
  cs <- .cyto_spillover_controls(
    x,
    parent = parent,
    type = type,
    channel_match = channel_match,
    axes_trans = axes_trans
  )
  
  # SPILLOVER COMPUTATION ------------------------------------------------------
  
  # BAGWELL METHOD
  if(grepl("^b", type, ignore.case = TRUE)) {
    
    # NOTE: CS - LIST PER CONTROL WITH NEGATIVE & POSITIVE EVENTS
    
    # MESSAGE
    message(
      "Computing spillover matrix using the Bagwell et al. (1993) method... \n"
    )
    # REFERENCE
    message(
      paste0(
        "C. B. Bagwell & E. G. Adams (1993). Fluorescence spectral ",
        "overlap compensation for any number of flow cytometry parameters. in:",
        " Annals of the New York Academy of Sciences, 677:167-184.", "\n"
      )
    )
    
    # GATED NEGATIVE AND POSITIVE POPULATIONS (TRANSFORMED)
    pops <- .cyto_spillover_pops(cs,
                                 axes_trans = axes_trans,
                                 axes_limits = axes_limits,
                                 ...)
    
    # CHANNELS - ONLY USE CHANNELS IN CONTROLS NOW
    channels <- names(pops)
    
    # COMPUTE SPILLOVER COEFFICIENTS PER CHANNEL
    spill <- do.call(
      "rbind",
      lapply(names(pops), function(z){
        # COMPUTE NEAGTIVE STATS
        neg_stats <- cyto_stats_compute(
          pops[[z]][["-"]],
          stat = "median",
          channels = channels,
          format = "wide",
          trans = axes_trans,
          markers = FALSE,
          details = FALSE
        )[, channels]
        # COMPUTE POSITIVE STATS
        pos_stats <- cyto_stats_compute(
          pops[[z]][["+"]],
          stat = "median",
          channels = channels,
          format = "wide",
          trans = axes_trans,
          markers = FALSE,
          details = FALSE
        )[, channels]
        # SUBTRACT BACKGROUND
        coef <- pos_stats - neg_stats
        # NORMALISE
        return(as.numeric(coef/coef[, z]))
      })
    )
    rownames(spill) <- names(pops)
    colnames(spill) <- names(pops)
    
  # AUTOSPILL - ROCA METHOD  
  } else {
    # MESSAGE
    message(
      "Computing spillover matrix using the Roca et al. (2021) method... \n"
    )
    # REFERENCE
    message(
      paste0(
        "Roca et al. (2021). AutoSpill is a principled framework that ",
        "simplifies the analysis of multichromatic flow cytometry data. Nature",
        " Communications 12(2890)."
      )
    )
    # AUTOSPILL - SPILLOVER MATRIX
    spill <- .cyto_asp_spill(cs)
  }
  
  # DEFAULT CSV FILENAME
  if (is.null(save_as)) {
    save_as <- paste0(format(Sys.Date(), "%d%m%y"), "-Spillover-Matrix.csv")
  }
  
  # EXPORT SPILLOVER MATRIX TO CSV FILE
  if (!cyto_class(save_as, "character")) {
    stop("'save_as' should be the name of a csv file.")
  } else {
    write_to_csv(spill, 
                 save_as)
  }
  
  return(spill)
}
