# CYTO_PLOT_EMPTY --------------------------------------------------------------

#' Create an empty cyto_plot
#'
#' \code{cyto_plot_empty} generates to base for cyto_plot by creating an empty
#' plot with border, axes, axes_text and titles. Data is subsequently added to
#' this base layer with \code{cyto_plot_point} or \code{cyto_plot_density}.
#'
#' @param x object of class \code{\link[flowCore:flowFrame-class]{flowFrame}}.
#' @param axes_trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transformation object will be used internally to ensure that the axes
#'   labels of the plot are appropriately transformed. The transformation object
#'   will NOT be applied to the flowFrame internally and should be applied to
#'   the flowFrame prior to plotting.
#' @param overlay a \code{flowFrame}, \code{flowSet} or list of
#'   \code{flowFrames} to be overlaid onto the plot.
#' @param xlim lower and upper limits of x axis (e.g. c(0,5)).
#' @param ylim lower and upper limits of y axis (e.g. c(0,5)).
#' @param limits indicates whether the axes limits should be based on the
#'   \code{"data"} or \code{"machine"}, set to "machine" by default to show
#'   complete axes ranges. This argument will only alter the upper axis limits,
#'   to modify the lower limits use \code{xlim} and \code{ylim}.
#' @param title title to use for the plot, set to the name of the sample by
#'   default. Title can be removed by setting this argument to \code{NA}.
#' @param xlab x axis label.
#' @param ylab y axis label.
#' @param density_modal logical indicating whether density should be normalised
#'   to mode and presented as a percentage. Set to \code{TRUE} by default.
#' @param density_smooth smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density.
#' @param density_stack numeric [0,1] indicating the degree of offset for
#'   overlaid populations, set to 0.5 by default.
#' @param axes_text logical vector of length 2 indicating whether axis text
#'   should be included for the x and y axes respectively, set to
#'   \code{c(TRUE,TRUE)} by default to display axes text on both axes.
#' @param axes_text_font numeric indicating the font to use for axes, set to 1
#'   for plain font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param axes_text_size character expansion for axis text.
#' @param axes_text_col colour of axis text.
#' @param axes_label_text_font numeric indicating the font to use for title, set
#'   to 1 for plain font by default. See \code{\link[graphics:par]{?par}} font
#'   for details.
#' @param axes_label_text_size character expansion for axis labels.
#' @param axes_label_text_col colour of axis labels.
#' @param title_text_font numeric indicating the font to use for title, set to 2
#'   for bold font by default. See \code{\link[graphics:par]{?par}} font for
#'   details.
#' @param title_text_size character expansion for plot title.
#' @param title_text_col colour for plot title.
#' @param border_line_type line type to use for plot border, set to 1 by default
#'   for a sold border.
#' @param border_line_width line width for plot border, set to 1 by default.
#' @param border_line_col line colour for plot border, set to "black" by
#'   default.
#' @param border_fill colour to use for the plot background, set to "white" by
#'   default.
#'
#' @importFrom graphics plot box axis title par
#' @importFrom methods formalArgs
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @examples
#' library(CytoRSuiteData)
#' 
#' # Construct an empty 2D plot with black background
#' cyto_plot_empty(Activation[1],
#'                 channels = c("FSC-A","SSC-A"),
#'                 border_fill = "black)
#'                 
#' # Construct an empty 1D plot
#' cyto_plot_empty(Activation[1],
#'                 channels = c("FSC-A),
#'                 overlay = Activation[2:4])
#'
#' @export
cyto_plot_empty <- function(x,
                            channels,
                            axes_trans = NA,
                            overlay = NA,
                            xlim = NA,
                            ylim = NA,
                            limits = "machine",
                            title = NA,
                            xlab = NA,
                            ylab = NA,
                            density_modal = TRUE,
                            density_smooth = 1.5,
                            density_stack = 0.5,
                            axes_text = c(TRUE,TRUE),
                            axes_text_font = 1,
                            axes_text_size = 1,
                            axes_text_col = "black",
                            axes_label_text_font = 1,
                            axes_label_text_size = 1.1,
                            axes_label_text_col = "black",
                            title_text_font = 2,
                            title_text_size = 1.1,
                            title_text_col = "black",
                            border_line_type = 1,
                            border_line_width = 1,
                            border_line_col = "black",
                            border_fill = "white",
                            legend = FALSE,
                            legend_text){
  
  # Prevent scientific notation on axes - reset on exit
  scipen <- getOption("scipen")
  options(scipen = 100000000)
  on.exit(options(scipen = scipen))
  
  # Extract current graphics parameters
  pars <- par("mar")
  
  # Reset graphics parameters on exit
  on.exit(par(pars))
  
  # Pull down arguments to named list
  args <- args_list()
  
  # Inherit arguments from cyto_plot_theme
  args <- .cyto_plot_theme_inherit(args)
  
  # Check channels
  channels <- cyto_channels_extract(args[["x"]],
                                    args[["channels"]],
                                    TRUE)
  
  # X axis limits
  if (.all_na(args[["xlim"]])) {
    .args <- formalArgs(".cyto_plot_axes_limits.flowFrame")
    args[["xlim"]] <- suppressWarnings(
      do.call(".cyto_plot_axes_limits.flowFrame",
              args[names(args) %in% .args])
    )[[1]]
  }
  
  # Y axis limits
  if (.all_na(args[["ylim"]])) {
    
    # Density distributions have different y axis limits
    if(length(channels) == 1){
      
      # Number of overlays
      ovn <- length(args[["overlay"]])
      
      # Combine x and overlay into the same list
      if(!.all_na(args[["overlay"]])){
        fr_list <- c(list(args[["x"]]), args[["overlay"]])
      }else{
        fr_list <- list(args[["x"]])
      }
      
      # Get kernel density for each list element
      fr_dens <- lapply(fr_list, function(x){
        
        .cyto_density(args[["x"]],
                      args[["channels"]],
                      args[["density_smooth"]],
                      args[["density_modal"]])
        
      })
      
      # Calculate the mean maximum y value for kernel densities
      if(args[["density_modal"]]){
        y_max <- 100
      }else{
        y_max <- mean(unlist(lapply(fr_dens, function(d){
          max(d$y) # max(NA) returns NA
        })), na.rm = TRUE)
      }
      
      # Stacked distributions require shifting of y values
      shft <- seq(0,
                  ovn * args[["density_stack"]] * y_max,
                  args[["density_stack"]] * y_max)
      
      # Shift distributions for stacking
      lapply(seq_len(length(fr_dens)), function(z){
        fr_dens[[z]]$y <<- fr_dens[[z]]$y + shft[z]
      })
      
      # YLIM 
      if(.all_na(args[["ylim"]])){
        args[["ylim"]] <- c(0, y_max + ovn * args[["density_stack"]] * y_max)
      }
      
    }else if(length(channels) == 2){
      .args <- formalArgs(".cyto_plot_axes_limits.flowFrame")
      args[["ylim"]] <- suppressWarnings(
        do.call(".cyto_plot_axes_limits.flowFrame",
              args[names(args) %in% .args])
      )[[2]]
    }

  }
  
  # Get Axis Breaks and Labels from trans if supplied
  if(is.null(getOption("CytoRSuite_cyto_plot_axes_text"))){
    axs <- .cyto_plot_axes_text(
      x = args[["x"]],
      channels = args[["channels"]],
      axes_trans = args[["axes_trans"]]
    )
  }else if(names(getOption("CytoRSuite_cyto_plot_axes_text")) != channels){
    axs <- .cyto_plot_axes_text(
      x = args[["x"]],
      channels = args[["channels"]],
      axes_trans = args[["axes_trans"]]
    )
  }else{
    axs <- getOption("CytoRSuite_cyto_plot_axes_text")
  }

  # x axis text
  xtext <- axs[[1]]

  # Y axis text for 1D density distributions
  if(length(channels) == 1) {
    ytext <- NA
  }else{
    ytext <- axs[[2]]
  }
  
  # Turn off y axis labels for stacked overlays
  if(!.all_na(args[["overlay"]]) & 
     args[["density_stack"]] != 0 &
     length(channels) == 1){
    
    args[["axes_text"]] <- c(args[["axes_text"]][1], FALSE)
    
  }
  
  # Set plot margins - set par("mar")
  .cyto_plot_margins(args[["x"]],
                     args[["overlay"]],
                     args[["legend"]],
                     args[["legend_text"]],
                     args[["title"]],
                     args[["axes_text"]])
  
  # Plot
  graphics::plot(1,
                 type = "n",
                 axes = FALSE,
                 xlim = args[["xlim"]],
                 ylim = args[["ylim"]],
                 xlab = "",
                 ylab = "",
                 bty = "n")
  
  # X axis
  if(args[["axes_text"]][1]){
    
    if(.all_na(xtext)){
      axis(1,
           font.axis = args[["axes_text_font"]],
           col.axis = args[["axes_text_col"]],
           cex.axis = args[["axes_text_size"]])
    }else{
      axis(1,
           at = xtext$at,
           labels = xtext$label,
           font.axis = args[["axes_text_font"]],
           col.axis = args[["axes_text_col"]],
           cex.axis = args[["axes_text_size"]])
    }
    
  }
  
  # Y axis
  if(args[["axes_text"]][2]){
    
    if(.all_na(ytext)){
      axis(2,
           font.axis = args[["axes_text_font"]],
           col.axis = args[["axes_text_col"]],
           cex.axis = args[["axes_text_size"]])
    }else{
      axis(2,
           at = ytext$at,
           labels = ytext$label,
           font.axis = args[["axes_text_font"]],
           col.axis = args[["axes_text_col"]],
           cex.axis = args[["axes_text_size"]])
    }
    
  }
  
  # Border
  box(which = "plot",
      lty = args[["border_line_type"]],
      lwd = args[["border_line_width"]],
      col = args[["border_line_col"]])
  
  
  # Border fill
  if(args[["border_fill"]] != "white"){
    rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],
         col = args[["border_fill"]],
         border = NA)
  }
  
  # Title
  if (!.all_na(args[["title"]])) {
    title(main = args[["title"]],
          cex.main = args[["title_text_size"]],
          col.main = args[["title_text_col"]],
          font.main = args[["title_text_font"]])
  }
  
  # X axis label - position labels closer if axes text is missing
  if(!args[["axes_text"]][1] & 
     !.all_na(args[["xlab"]])){
    
    title(xlab = args[["xlab"]],
          font.lab = args[["axes_label_text_font"]],
          col.lab = args[["axes_label_text_col"]],
          cex.lab = args[["axes_label_text_size"]],
          mgp = c(2,0,0))
    
  }else if(args[["axes_text"]][1] & 
           !.all_na(args[["xlab"]])){
    
    title(xlab = args[["xlab"]],
          font.lab = args[["axes_label_text_font"]],
          col.lab = args[["axes_label_text_col"]],
          cex.lab = args[["axes_label_text_size"]])
    
  }
  
  # Y axis label - position labels closer if axes text is missing
  if(!args[["axes_text"]][2] & 
     !.all_na(args[["ylab"]])){
    
    title(ylab = args[["ylab"]],
          font.lab = args[["axes_label_text_font"]],
          col.lab = args[["axes_label_text_col"]],
          cex.lab = args[["axes_label_text_size"]],
          mgp = c(2,0,0))
    
  }else if(args[["axes_text"]][2] & 
           !.all_na(args[["ylab"]])){
    
    title(ylab = args[["ylab"]],
          font.lab = args[["axes_label_text_font"]],
          col.lab = args[["axes_label_text_col"]],
          cex.lab = args[["axes_label_text_size"]])
    
  }

}

# CYTO_PLOT_WINDOW -------------------------------------------------------------

#' Check Operating System & Open New Graphics Device
#'
#' \code{cyto_plot_window} is used internally by cyto_plot to open an
#' OS-specific interactive garphics device to facilitate gate drawing. Mac users
#' will need to install \href{https://www.xquartz.org/}{XQuartz} for this
#' functionality.
#'
#' @author Dillon Hammill, \email{Dillon.Hammill@anu.edu.au}
#'
#' @import grDevices
#'
#' @examples
#' \dontrun{
#' # Open platform-specific graphics device
#' cyto_plot_window()
#' }
#' 
#' @export
cyto_plot_window <- function() {
  if (.Platform$OS.type == "windows") {

    # open windows graphics device
    grDevices::windows()
  } else if (.Platform$OS.type == "unix") {
    if (Sys.info()["sysname"] == "Linux") {

      # Cairo needed for semi-transparency
      X11(type = "cairo")
    } else if (Sys.info()["sysname"] == "Darwin") {

      # open XQuartz graphics device
      quartz()
    }
  }
}

# CYTO_PLOT_SAVE ---------------------------------------------------------------

#' Save High Resolution cyto_plot Images
#'
#' @param file name of the file to which the plot should be saved (including the
#'   file extension). Supported file formats include png, tiff jpeg and pdf.
#' @param width numeric indicating the width of exported plot in \code{units},
#'   set to 7 by default for image with width of 7 inches.
#' @param height numeric indicating the height of the exported plot in
#'   \code{units}, set to 7 by default for image with height of 7 inches.
#' @param units units to be used to set plot size, can be either pixels
#'   (\code{px}), inches (\code{inches}), centimetres (\code{cm}) or millimetres
#'   (\code{mm}). Set to \code{"in"} by default.
#' @param res resolution in ppi, set to 300 by default.
#' @param multiple logical indicating whether multiple pages should be saved to
#'   separate numbered files, set to \code{TRUE} by default.
#' @param ... additional arguments for the appropriate \code{png()},
#'   \code{tiff()}, \code{jpeg()} or \code{pdf} graphics devices.
#'
#' @importFrom tools file_ext file_path_sans_ext
#' @importFrom grDevices png tiff jpeg pdf
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @examples
#' library(CytoRSuiteData)
#' 
#' # Load samples into GatingSet
#' fs <- Activation
#' gs <- GatingSet(fs)
#' 
#' # Apply compensation
#' gs <- compensate(gs, fs[[1]]@description$SPILL)
#' 
#' # Transform fluorescent channels
#' trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(gs))
#' gs <- transform(gs, trans)
#' 
#' # Apply gatingTemplate
#' gt <- Activation_gatingTemplate
#' gating(gt, gs)
#' 
#' # Save png image of gating scheme after plotting
#' cyto_plot_save("Gating-Scheme.png",
#'   width = 20,
#'   height = 16
#' )
#' cyto_plot_gating_scheme(gs[[1]])
#' 
#' # Save multiple pages to the same pdf file
#' cyto_plot_save("CD4-T-Cells.pdf",
#'   height = 8,
#'   width = 16,
#'   multiple = TRUE
#' )
#' cyto_plot(gs,
#'   parent = "CD4 T Cells",
#'   alias = "",
#'   channels = c("Alexa Fluor 647-A", "7-AAD-A"),
#'   layout = c(1, 2)
#' )
#' @export
cyto_plot_save <- function(file,
                           width = 7,
                           height = 7,
                           units = "in",
                           res = 300,
                           multiple = FALSE,
                           ...) {

  # File missing extension
  if (file_ext(file) == "") {

    # Modify file name to export png by default
    file <- paste0(file, ".png")
  }

  # Save separate pages to separate number files
  if (multiple == TRUE & file_ext(file) != "pdf") {
    file <- paste0(
      file_path_sans_ext(file),
      "%03d", ".",
      file_ext(file)
    )
  }

  # png device
  if (file_ext(file) == "png") {
    png(
      filename = file,
      width = width,
      height = height,
      units = units,
      res = res,
      ...
    )
  } else if (file_ext(file) == "tiff") {
    tiff(
      filename = file,
      width = width,
      height = height,
      units = units,
      res = res,
      ...
    )
  } else if (file_ext(file) == "jpeg") {
    jpeg(
      filename = file,
      width = width,
      height = height,
      units = units,
      res = res,
      ...
    )
  } else if (file_ext(file) == "pdf") {
    pdf(
      file = file,
      width = width,
      height = height,
      onefile = multiple,
      ...
    )
  } else {
    stop(paste("Can't save file to", file_ext(file), "format."))
  }

  # Set global option to notify cyto_plot when dev.off() is required for saving
  options("CytoRSuite_cyto_plot_save" = TRUE)
}

# CYTO_PLOT_LAYOUT -------------------------------------------------------------

#' Set Panel Layout for cyto_plot
#'
#' \code{cyto_plot_layout()} sets the panel layout dimensions for combining
#' different types of cyto_plot plots. Make a call to \code{cyto_plot_layout()}
#' prior to making multiple calls to \code{cyto_plot()}.
#'
#' @param nrow number of rows to include in the panel layout.
#' @param ncol number of columns to include in the panel layout.
#' @param by chracter string indicating whether the plot should be filled by
#'   \code{"row"} or \code{"column"}, set to \code{"row"} by default.
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @examples
#' library(CytoRSuiteData)
#' 
#' # Load samples into GatingSet
#' fs <- Activation
#' gs <- GatingSet(fs)
#' 
#' # Apply compensation
#' gs <- compensate(gs, fs[[1]]@description$SPILL)
#' 
#' # Transform fluorescent channels
#' trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(gs))
#' gs <- transform(gs, trans)
#' 
#' # Apply gatingTemplate
#' gt <- Activation_gatingTemplate
#' gating(gt, gs)
#' 
#' # Set out plot layout
#' cyto_plot_layout(1, 2)
#' 
#' # Add 2D plot
#' cyto_plot(gs[[4]],
#'   parent = "CD4 T Cells",
#'   alias = "",
#'   channels = c("Alexa Fluor 647-A", "7-AAD-A"),
#'   layout = FALSE
#' )
#' 
#' # Add 1D plot
#' cyto_plot(gs,
#'   parent = "CD4 T Cells",
#'   alias = "",
#'   channels = "7-AAD-A",
#'   density_stack = 0.6,
#'   layout = FALSE
#' )
#' @export
cyto_plot_layout <- function(nrow,
                             ncol,
                             by = "row") {

  # Use mfrow
  if (by %in% c("r", "row")) {
    par(mfrow = c(nrow, ncol))

    # Use mfcol
  } else if (by %in% c("c", "col", "column")) {
    par(mfcol = c(nrow, ncol))
  }
}

# CYTO_PLOT_COMPLETE -----------------------------------------------------------

#' Indicate Completion of Custom cyto_plot Layout for Saving
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @examples
#' library(CytoRSuiteData)
#' 
#' # Load samples into GatingSet
#' fs <- Activation
#' gs <- GatingSet(fs)
#' 
#' # Apply compensation
#' gs <- compensate(gs, fs[[1]]@description$SPILL)
#' 
#' # Transform fluorescent channels
#' trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(gs))
#' gs <- transform(gs, trans)
#' 
#' # Apply gatingTemplate
#' gt <- Activation_gatingTemplate
#' gating(gt, gs)
#' 
#' # Save custom plot
#' cyto_plot_save("Custom.png",
#'   height = 8,
#'   width = 16
#' )
#' 
#' # Set out plot layout
#' cyto_plot_layout(1, 2)
#' 
#' # Add 2D plot
#' cyto_plot(gs[[4]],
#'   parent = "CD4 T Cells",
#'   alias = "",
#'   channels = c("Alexa Fluor 647-A", "7-AAD-A"),
#'   layout = FALSE
#' )
#' 
#' # Add 1D plot
#' cyto_plot(gs,
#'   parent = "CD4 T Cells",
#'   alias = "",
#'   channels = "7-AAD-A",
#'   density_stack = 0.6,
#'   layout = FALSE
#' )
#' 
#' # Signal that the plot is complete
#' cyto_plot_complete()
#' @export
cyto_plot_complete <- function() {

  # Close graphics device
  dev.off()
}

# CYTO_PLOT_THEME --------------------------------------------------------------

#' Create custom themes for cyto_plot
#'
#' \code{cyto_plot_theme} provides an easy way to alter the theme used by
#' \code{cyto_plot}. By calling \code{cyto_plot_theme} prior to plotting,
#' subsequent plots will inherit these arguments so there is no need to supply
#' them manually each time. For a complete list of supported arguments see
#' \code{cyto_plot_theme_args}.
#'
#' @param ... arguments supported by cyto_plot_theme.
#'
#' @examples 
#' # Make all plots have a black background
#' cyto_plot_theme(border_fill = "black")
#' 
#' # Black ground with custom colour scale for points and purple gates
#' cyto_plot_theme(border_fill = "black",
#'                 point_col_scale = c("cyan",
#'                                     "green",
#'                                     "yellow",
#'                                     "orange",
#'                                     "red",
#'                                     "darkred"),
#'                 gate_line_col = "magenta")
#' 
#' # Reset to default setting
#' cyto_plot_theme_reset()
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @export
cyto_plot_theme <- function(...) {

  # cyto_plot will pull down these arguments

  # Arguments as named list
  args <- list(...)
  
  # Empty list set theme to NULL
  if(length(args) == 0){
    args <- NULL
  }else{
    # Check supplied arguments are supported.
    if(!all(names(args) %in% cyto_plot_theme_args())){
      message("Some supplied arguments are not supported for cyto_plot_theme.")
    }

    # Restrict list to supported arguments only
    args <- args[names(args) %in% cyto_plot_theme_args()]
  }

  # Assign arguments to CytoRSuite_cyto_plot_theme option
  options("CytoRSuite_cyto_plot_theme" = args)
  
}

#' Reset cyto_plot_theme to default settings
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @export
cyto_plot_theme_reset <- function() {

  # Set CytoRSuite_cyto_plot_theme option to NULL
  options("CytoRSuite_cyto_plot_theme" = NULL)
  
}

#' Get supported cyto_plot_theme arguments
#' 
#' @return vector of argument names supported by cyto_plot_theme.
#' 
#' @examples 
#' cyto_plot_theme_args()
#' 
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#' 
#' @export
cyto_plot_theme_args <- function(){
  
  c("limits",
  "popup",
  "density_modal",
  "density_smooth",
  "density_stack",
  "density_cols",
  "density_fill_alpha",
  "density_line_type",
  "density_line_width",
  "density_line_col",
  "axes_text",
  "axes_text_font",
  "axes_text_size",
  "axes_text_col",
  "axes_label_text_font",
  "axes_label_text_size",
  "axes_label_text_col",
  "title_text_font",
  "title_text_size",
  "title_text_col",
  "legend",
  "legend_text_font",
  "legend_text_size",
  "legend_text_col",
  "legend_line_col",
  "legend_box_fill",
  "gate_line_type",
  "gate_line_width",
  "gate_line_col",
  "label",
  "label_text_font",
  "label_text_size",
  "label_text_col",
  "label_box_alpha",
  "border_fill",
  "border_line_type",
  "border_line_width",
  "border_line_col",
  "point_shape",
  "point_size",
  "point_col_scale",
  "point_cols",
  "point_col",
  "point_alpha",
  "contour_line_type",
  "contour_line_width",
  "contour_line_col")
  
}
