## CYTO_GGPLOT -----------------------------------------------------------------

#' Convert plots created by cyto_plot() into ggplot2 objects
#'
#' Much of the analysis and data visualisation downstream of CytoExploreR will
#' be performed by the ggplot2 package. \code{cyto_ggplot} makes it easy to
#' convert plots generated by \code{cyto_plot()} into grob or ggplot objects
#' that can easily be arranged with other ggplot objects using the
#' \code{cowplot} or \code{patchwork} packages.
#'
#' @param ... arguments passed to \code{\link{cyto_plot}}.
#' @param grob logical indicating whether a grob should be returned instead of a
#'   ggplot2 object, set to FALSE by default.
#'
#' @return a plot produced by \code{cyto_plot()} converted to either a grob or
#'   ggplot2 object.
#'
#' @author Dillon Hammill, \email{Dillon.Hammill@anu.edu.au}
#'
#' @examples
#' \dontrun{
#' library(CytoExploreRData)
#'
#' gs <- GatingSet(Activation)
#'
#' g <- cyto_ggplot(
#' gs[1],
#' parent = "root",
#' channels = c("FSC-A", "SSC-A")
#' )
#' g
#'
#' }
#'
#' @export
cyto_ggplot <- function(...,
                        grob = FALSE) {
  
  # REQUIRE GGPLOTIFY
  cyto_require(
    "ggplotify"
  )
  
  # CREATE FUNCTION CALLING CYTO_PLOT
  cyto_plot_fun <- function() {
    cyto_plot(
      ...
    )
  }
  
  # CONVERT CYTO_PLOT TO GROB
  grb <- cyto_func_call(
    "ggplotify::as.grob", 
    list(
      plot = cyto_plot_fun
    )
  )
  
  # RETURN GROB
  if(grob) {
    return(grb)
    # RETURN GGPLOT OBJECT
  } else {
    return(
      cyto_func_call(
        "ggplotify::as.ggplot", 
        list(plot = grb)
      )
    )
  }
  
}

## CYTO_PLOT_ANIMATE -----------------------------------------------------------

#' Create cyto_plot animations
#'
#' @param x a list of recorded plots returned by a call to \code{cyto_plot()} or
#'   the names of a series of PNG files generated by \code{cyto_plot_save()}.
#' @param save_as name of a GIF file to which the animated plot should be saved.
#' @param height GIF height in pixels, set to 800 pixels by default.
#' @param width GIF width in pixels, set to 800 pixels by default.
#' @param delay time in seconds to display each image in the animation, set to 1
#'   second by default.
#' @param ... additional arguments passed to \code{gifski::gifski()}.
#'
#' @return create a GIF file in the current working directory containing the
#'   animated plot.
#'
#' @author Dillon Hammill, \email{Dillon.Hammill@anu.edu.au}
#'
#' @examples
#' \dontrun{
#' library(CytoExploreRData)
#' 
#' gs <- GatingSet(Activation)
#' 
#' gs <- cyto_compensate(gs)
#' 
#' gs <- cyto_transform(gs)
#' 
#' gs <- cyto_gatingTemplate_apply(gs, Activation_gatingTemplate)
#' 
#' cyto_plot_save("cyto_plot-1.png")
#' cyto_plot(
#' gs[29], 
#' parent = "CD4 T Cells", 
#' channels = c("CD44", "CD69"), 
#' title = "0 nM OVA"
#' )
#' 
#' cyto_plot_save("cyto_plot-2.png")
#' cyto_plot(
#' gs[30], 
#' parent = "CD4 T Cells", 
#' channels = c("CD44", "CD69"), 
#' title = "5 nM OVA"
#' )
#' 
#' cyto_plot_save("cyto_plot-3.png")
#' cyto_plot(
#' gs[31], 
#' parent = "CD4 T Cells", 
#' channels = c("CD44", "CD69"), 
#' title = "50 nM OVA"
#' )
#' 
#' cyto_plot_save("cyto_plot-4.png")
#' cyto_plot(
#' gs[32], 
#' parent = "CD4 T Cells", 
#' channels = c("CD44", "CD69"), 
#' title = "50 nM OVA"
#' )
#' 
#' cyto_plot_animate(
#' c("cyto_plot-1.png", 
#' "cyto_plot-2.png", 
#' "cyto_plot-3.png", 
#' "cyto_plot-4.png"),
#' save_as = "cyto_plot_animation.gif"
#' )
#' 
#' }
#'
#' @seealso \code{\link{cyto_plot}}
#' @seealso \code{\link{cyto_plot_save}}
#'
#' @export
cyto_plot_animate <- function(x,
                              save_as = NULL,
                              height = 800,
                              width = 800,
                              delay = 1,
                              ...) {
  
  # SAVE_AS REQUIRED
  if(is.null(save_as)) {
    stop(
      "Supply a name for the exported GIF file to 'save_as'."
    )
  } else {
    save_as <- file_ext_append(save_as, ".gif")
  }
  
  # REQUIRE GIFSKI PACKAGE
  cyto_require(
    "gifski"
  )
  
  # PNG FILE NAMES
  args <- list(
    png_files = x,
    gif_file = save_as,
    delay = delay,
    height = height,
    width = width,
    ...
  )
  cyto_func_call(
    "gifski::gifski",
    args
  )
  
  # NO RETURN VALUE
  invisible(NULL)
  
}