#' Add boxed text labels to cyto_plot
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency. In the absence of a gate,
#' users can manually specify the label position using the \code{text_x} and
#' \code{text_y} arguments.
#'
#' @param x object of class \code{"flowFrame"}.
#' @param gate object of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}},
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}},
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}, \code{"list"} or
#'   \code{\link[flowCore:filters-class]{filters}}.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text character string to include in the label above the statistic
#'   (e.g. population name(s)).
#' @param stat indicates the type of statistic to include in the label, can be
#'   either code{"count"}, \code{"median"}, \code{"mean"}, \code{"mode"},
#'   \code{"geo mean"} or \code{"CV"}. \code{stat} is set to \code{"median"} by
#'   default. Statistics for fluorescent intensity are calculated for the entire
#'   distribution. Only count and percent statistics are supported for 2D plots.
#' @param text_x vector containing the x co-ordinates for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordinates for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background,
#'   set to \code{0.6} by default.
#' @param density_smooth smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density for mode
#'   calculation.
#' @param plot logical indicating whether the labels should be added to the
#'   plot. Can be turned off to obtain co-ordinates for the labels.
#' @param ... passes additional list method arguments to other methods.
#'
#' @return add a boxed text label to an existing plot.
#'
#' @importFrom flowCore Subset parameters
#'
#' @examples
#' #' library(CytoRSuiteData)
#'
#' # Load in samples
#' fs <- Activation
#' gs <- GatingSet(fs)
#'
#' # Apply compensation
#' gs <- compensate(gs, fs[[1]]@description$SPILL)
#'
#' # Transform fluorescent channels
#' trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(fs))
#' gs <- transform(gs, trans)
#'
#' # Gate using gate_draw
#' gating(Activation_gatingTemplate, gs)
#'
#' # Plot
#' cyto_plot(gs[[4]],
#'   parent = "T Cells",
#'   channels = c("Alexa Fluor 488-A", "Alexa Fluor 700-A")
#' )
#'
#' # Labels without gates - position using text_x and text_y
#' cyto_plot_label(getData(gs, "T Cells")[[4]],
#'   gate = NULL,
#'   channels = c("Alexa Fluor 488-A", "Alexa Fluor 700-A"),
#'   trans = trans,
#'   text = c("CD4 T Cells", "CD8 T Cells"),
#'   text_x = c(3.1, 1),
#'   text_y = c(-0.2, 3.2)
#' )
#'
#' #' # Plot
#' cyto_plot(gs[[4]],
#'   parent = "CD4 T Cells",
#'   channels = "7-AAD-A"
#' )
#'
#' # CD69+ CD4 T Cells gate
#' gt <- getGate(gs, "CD69+ CD4 T Cells")[[1]]
#' cyto_plot_gate(gt,
#'   channels = "7-AAD-A"
#' )
#'
#' # Labels
#' cyto_plot_label(getData(gs, "CD4 T Cells")[[4]],
#'   gate = gt,
#'   trans = trans,
#'   channels = "7-AAD-A",
#'   text = c("CD69+"),
#'   stat = "freq",
#'   text_col = "blue"
#' )
#'
#' #' # Plot
#' cyto_plot(gs[[4]],
#'   parent = "root",
#'   channels = c("FSC-A", "SSC-A")
#' )
#'
#' # Cells gate
#' gt <- getGate(gs, "Cells")[[1]]
#' cyto_plot_gate(gt,
#'   channels = c("FSC-A", "SSC-A")
#' )
#'
#' # Labels
#' cyto_plot_label(getData(gs, "root")[[4]],
#'   gate = gt,
#'   trans = trans,
#'   channels = c("FSC-A", "SSC-A"),
#'   text = "Cells",
#'   stat = "freq",
#'   text_col = "magenta",
#'   text_size = 1.2
#' )
#'
#' #' # Plot
#' cyto_plot(gs[[4]],
#'   parent = "Live Cells",
#'   channels = c("APC-Cy7-A", "PE-A")
#' )
#'
#' # T Cells gate
#' gt <- getGate(gs, "T Cells")[[1]]
#' cyto_plot_gate(gt,
#'   channels = c("APC-Cy7-A", "PE-A")
#' )
#'
#' # Labels
#' cyto_plot_label(getData(gs, "Live Cells")[[4]],
#'   gate = gt,
#'   trans = trans,
#'   channels = c("APC-Cy7-A", "PE-A"),
#'   text = "T Cells",
#'   stat = "count",
#'   text_col = "magenta",
#'   text_size = 1.2,
#'   box_alpha = 1
#' )
#'
#' #' # Plot
#' cyto_plot(gs[[4]],
#'   parent = "Live Cells",
#'   channels = c("APC-Cy7-A", "PE-A")
#' )
#'
#' # T Cells & Dendritic Cells gates
#' gts <- list(getGate(gs, "T Cells")[[1]], getGate(gs, "Dendritic Cells")[[1]])
#' cyto_plot_gate(gts,
#'   channels = c("APC-Cy7-A", "PE-A")
#' )
#'
#' # Labels
#' cyto_plot_label(getData(gs, "Live Cells")[[4]],
#'   gate = gts,
#'   trans = trans,
#'   channels = c("APC-Cy7-A", "PE-A"),
#'   text = c("T Cells", "Dendritic Cells"),
#'   stat = "count",
#'   text_col = c("magenta", "purple"),
#'   text_size = 1.2,
#'   box_alpha = 1
#' )
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @export
cyto_plot_label <- function(x, gate, ...) {
  UseMethod("cyto_plot_label", gate)
}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.default <- function(x, gate, ...) {

  # Dispatch to NULL method if gate is NA
  if (.all_na(gate)) {
    cyto_plot_label.NULL(x, gate = NULL, ...)
  } else {
    stop(paste0(
      "cyto_plot_label does not support gate objects of class ",
      class(gate), "!"
    ))
  }
}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.NULL <- function(x,
                                 gate,
                                 trans = NA,
                                 channels,
                                 text = NA,
                                 stat = NA,
                                 text_x = NA,
                                 text_y = NA,
                                 text_font = 2,
                                 text_size = 0.8,
                                 text_col = "black",
                                 box_alpha = 0.6,
                                 density_smooth = 0.6,
                                 plot = TRUE, ...) {

  # Check statistic
  if (!.all_na(stat)) {
    stat <- .cyto_stat_check(stat)
  }

  # Channels needed to position label
  if (missing(channels)) {
    stop("Supply channel/marker(s) to contruct the plot.")
  }

  # Missing transList
  if (stat %in% c(
    "median",
    "mode",
    "mean",
    "geo mean",
    "CV"
  )) {
    if (is.null(cyto_transform_convert(trans))) {
      stop(
        paste("Supply transformList/transformerList to calculate", stat, ".")
      )
    }
  }

  # Stats not supported in 2D
  if (length(channels) == 2 &
    stat %in% c(
      "mean",
      "median",
      "mode",
      "geo mean",
      "freq",
      "CV"
    )) {
    stop("Only count is supported for 2D plots without gates.")
  }

  # Missing text
  if (.all_na(text) & !.all_na(stat)) {
    message(
      paste("No text supplied for labels - labels will show", stat, "only.")
    )
  }

  # Calculate statistics using cyto_stats_compute
  if (!.all_na(stat)) {
    st <- cyto_stats_compute(x,
      channels = channels,
      trans = trans,
      stat = stat,
      format = "long",
      density_smooth = density_smooth
    )
    st <- round(st[, ncol(st)], 2)
  }

  # Label co-ordinate
  text_xy <- .cyto_plot_label_center(gate,
    channels = channels,
    text_x = text_x,
    text_y = text_y
  )

  # Add labels to plot?
  if(plot == TRUE){
    # Add labels
    if (!.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = paste(text, st, sep = "\n"),
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (!.all_na(text) & .all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = text,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = st,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    }
  }
  
  invisible(text_xy)

}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.rectangleGate <- function(x,
                                          gate,
                                          trans = NA,
                                          channels,
                                          text = NA,
                                          stat = NA,
                                          text_x = NA,
                                          text_y = NA,
                                          text_font = 2,
                                          text_size = 0.8,
                                          text_col = "black",
                                          box_alpha = 0.6,
                                          density_smooth = 0.6,
                                          plot = TRUE, ...) {

  # Check statistic
  if (!.all_na(stat)) {
    stat <- .cyto_stat_check(stat)
  }

  # Channels needed to position label
  if (missing(channels)) {
    stop("Supply channel/marker(s) to contruct the plot.")
  }

  # Only count and percent supported in 2D
  if (length(channels) == 2 & !stat %in% c("count", "freq")) {
    stop("Only count and percent statistics are supported in 2D plots.")
  }

  # Missing transList
  if (stat %in% c("median", "mode", "mean", "geo mean")) {
    if (is.null(cyto_transform_convert(trans))) {
      stop(
        paste("Supply transformList/transformerList to calculate", stat, ".")
      )
    }
  }

  # 2D gate in 1D plot
  if (length(channels) == 1 & length(parameters(gate)) == 2) {
    gate <- gate[channels]
  }

  # Missing text
  if (.all_na(text) & !.all_na(stat)) {
    message(
      paste("No text supplied for labels - labels will show", stat, "only.")
    )
  }

  # Apply gate to flowFrame
  y <- Subset(x, gate)

  # Calculate statistics using cyto_stats_compute
  if (!.all_na(stat)) {
    if (stat == "freq") {
      st <- .cyto_count(y) / .cyto_count(x) * 100
      st <- sprintf("%.2f %%", st)
    } else {
      st <- cyto_stats_compute(y,
        channels = channels,
        trans = trans,
        stat = stat,
        format = "long",
        density_smooth = density_smooth
      )
      st <- round(st[, ncol(st)], 2)
    }
  }

  # Label co-ordinate
  text_xy <- .cyto_plot_label_center(gate,
    channels = channels,
    text_x = text_x,
    text_y = text_y
  )

  # Add labels to plot?
  if(plot == TRUE){
    # Add labels
    if (!.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = paste(text, st, sep = "\n"),
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (!.all_na(text) & .all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = text,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = st,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    }
  }
  
  invisible(text_xy)

}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.polygonGate <- function(x,
                                        gate,
                                        channels,
                                        trans = NA,
                                        text = NA,
                                        stat = NA,
                                        text_x = NA,
                                        text_y = NA,
                                        text_font = 2,
                                        text_size = 0.8,
                                        text_col = "black",
                                        box_alpha = 0.6,
                                        density_smooth = 0.6,
                                        plot = TRUE, ...) {

  # Check statistic
  if (!.all_na(stat)) {
    stat <- .cyto_stat_check(stat)
  }

  # Channels needed to position label
  if (missing(channels)) {
    stop("Supply channel/marker(s) to contruct the plot.")
  }

  # Only count and percent supported
  if (!stat %in% c("count", "freq")) {
    stop("Only 'count' and 'percent' are supported for gated 2D plots.")
  }

  # Missing text
  if (.all_na(text) & !.all_na(stat)) {
    message(
      paste("No text supplied for labels - labels will show", stat, "only.")
    )
  }

  # Apply gate to flowFrame
  y <- Subset(x, gate)

  # Calculate statistics using cyto_stats_compute
  if (!.all_na(stat)) {
    if (stat == "freq") {
      st <- .cyto_count(y) / .cyto_count(x) * 100
      st <- sprintf("%.2f %%", st)
    } else {
      st <- cyto_stats_compute(y,
        channels = channels,
        trans = trans,
        stat = stat,
        format = "long",
        density_smooth = density_smooth
      )
      st <- round(st[, ncol(st)], 2)
    }
  }

  # Label co-ordinate
  text_xy <- .cyto_plot_label_center(gate,
    channels = channels,
    text_x = text_x,
    text_y = text_y
  )

  # Add labels to plot?
  if(plot == TRUE){
    # Add labels
    if (!.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = paste(text, st, sep = "\n"),
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (!.all_na(text) & .all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = text,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = st,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    }
  }
  
  invisible(text_xy)
  
}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.ellipsoidGate <- function(x,
                                          gate,
                                          channels,
                                          trans = NA,
                                          text = NA,
                                          stat = NA,
                                          text_x = NA,
                                          text_y = NA,
                                          text_font = 2,
                                          text_size = 0.8,
                                          text_col = "black",
                                          box_alpha = 0.6,
                                          density_smooth = 0.6,
                                          plot = TRUE, ...) {

  # Check statistic
  if (!.all_na(stat)) {
    stat <- .cyto_stat_check(stat)
  }

  # Channels needed to position label
  if (missing(channels)) {
    stop("Supply channel/marker(s) to contruct the plot.")
  }

  # Only count and percent supported
  if (!stat %in% c("count", "freq")) {
    stop("Only 'count' and 'percent' are supported for gated 2D plots.")
  }

  # Missing text
  if (.all_na(text) & !.all_na(stat)) {
    message(
      paste("No text supplied for labels - labels will show", stat, "only.")
    )
  }


  # Apply gate to flowFrame
  y <- Subset(x, gate)

  # Calculate statistics using cyto_stats_compute
  if (!.all_na(stat)) {
    if (stat == "freq") {
      st <- .cyto_count(y) / .cyto_count(x) * 100
      st <- sprintf("%.2f %%", st)
    } else {
      st <- cyto_stats_compute(y,
        channels = channels,
        trans = trans,
        stat = stat,
        format = "long",
        density_smooth = density_smooth
      )
      st <- round(st[, ncol(st)], 2)
    }
  }

  # Label co-ordinates
  text_xy <- .cyto_plot_label_center(gate,
    channels = channels,
    text_x = text_x,
    text_y = text_y
  )

  # Add labels to plot?
  if(plot == TRUE){
    # Add labels
    if (!.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = paste(text, st, sep = "\n"),
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (!.all_na(text) & .all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = text,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    } else if (.all_na(text) & !.all_na(stat)) {
      .boxed.labels(
        x = text_xy[1,],
        y = text_xy[2,],
        labels = st,
        border = FALSE,
        font = text_font,
        col = text_col,
        alpha.bg = box_alpha,
        cex = text_size
      )
    }
  }
  
  invisible(text_xy)
  
}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.list <- function(x,
                                 gate,
                                 trans = NA,
                                 channels,
                                 text = NA,
                                 stat = NA,
                                 text_x = NA,
                                 text_y = NA,
                                 text_font = 2,
                                 text_size = 0.8,
                                 text_col = "black",
                                 box_alpha = 0.6,
                                 density_smooth = 0.6,
                                 plot = TRUE, ...) {

  # List of filters to list of gate objects
  gate <- unlist(gate)

  # Get co-ordinates of gate centers for labels
  text_xy <- .cyto_plot_label_center(gate,
                                     channels = channels,
                                     text_x = text_x,
                                     text_y = text_y)
  
  # Update x co-ordinates if not supplied
  if(.all_na(text_x)){
    text_x <- text_xy[1,]
  }
  
  # Update y coordinates if not supplied
  if(.all_na(text_y)){
    text_y <- text_xy[2,]
  }
  
  # Get adjusted co-ordinates if not manually supplied
    if(is.null(getOption("CytoRSuite_cyto_plot_label_coords"))){
      text_xy <- .cyto_plot_label_offset(x,
                                        gate = gate,
                                        channels = channels,
                                        text = text,
                                        text_x = text_x,
                                        text_y = text_y,
                                        stat = stat,
                                        text_size = text_size
      )
    }
  
  # Update co-ordinates
  text_x <- text_xy[1,]
  text_y <- text_xy[2,]
  
  # Make calls to cyto_plot_label
  if(plot == TRUE){
  mapply(
      function(gate,
                     text,
                     stat,
                     text_x,
                     text_y,
                     text_font,
                     text_col,
                     text_size,
                     box_alpha) {
        cyto_plot_label(
          x = x,
          trans = trans,
          gate = gate,
          channels = channels,
          text = text,
          stat = stat,
          text_x = text_x,
          text_y = text_y,
          text_font = text_font,
          text_col = text_col,
          text_size = text_size,
          box_alpha = box_alpha,
          plot = plot
        )
      }, gate,
      text,
      stat,
      text_x,
      text_y,
      text_font,
      text_col,
      text_size,
      box_alpha
    , SIMPLIFY = FALSE)
  }
  
  invisible(text_xy)
    
}

#' @rdname cyto_plot_label
#' @export
cyto_plot_label.filters <- function(x,
                                    gate,
                                    trans = NA,
                                    channels,
                                    text = NA,
                                    stat = NA,
                                    text_x = NA,
                                    text_y = NA,
                                    text_font = 2,
                                    text_size = 0.8,
                                    text_col = "black",
                                    box_alpha = 0.6,
                                    density_smooth = 0.6,
                                    plot = TRUE, ...) {

  # Convert gate to a list of gates
  gate <- unlist(gate)

  # Make calls to cyto_plot_label list method
  text_xy <- cyto_plot_label(
    x = x,
    trans = trans,
    gate = gate,
    channels = channels,
    text = text,
    stat = stat,
    text_x = text_x,
    text_y = text_y,
    text_font = text_font,
    text_col = text_col,
    text_size = text_size,
    box_alpha = box_alpha,
    density_smooth = density_smooth,
    offset = offset,
    plot = plot
  )
  
  invisible(text_xy)
}
