#' Plot Population Density Distribution in All Channels
#'
#' @param x object of class \code{\link[flowCore:flowFrame-class]{flowFrame}},
#'   \code{\link[flowCore:flowSet-class]{flowSet}},
#'   \code{\link[flowWorkspace:GatingHierarchy-class]{GatingHierarchy}} or
#'   \code{\link[flowWorkspace:GatingSet-class]{GatingSet}}.
#' @param ... additional method-specific arguments.
#'
#' @importFrom flowCore exprs
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{plotCytoExprs,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowSet-method}}
#' @seealso \code{\link{plotCytoExprs,GatingHierarchy-method}}
#' @seealso \code{\link{plotCytoExprs,GatingSet-method}}
#'
#' @export
setGeneric(name = "plotCytoExprs",
           def = function(x, ...){standardGeneric("plotCytoExprs")}
)

#' Plot Population Density Distribution in All Channels - flowFrame Method
#'
#' @param x object of class \code{\link[flowCore:flowFrame-class]{flowFrame}}.
#' @param channels a vector channels to use to construct the plots, set to all
#'   channels by default.
#' @param transList object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transList object will be used internally to ensure axes labels of the plot
#'   are appropriately transformed. The transList will NOT be applied to the
#'   flowFrame internally and should be applied to the flowFrame prior to
#'   plotting.
#' @param mfrow vector of grid dimensions \code{c(#rows,#columns)}.
#' @param title a title for the plots, set to the file name of x by default.
#' @param ... additional arguments passed to \code{\link{plotCyto1d,flowFrame-method}}.
#'
#' @importFrom flowCore exprs
#' @importFrom grDevices n2mfrow
#' @importFrom graphics par mtext
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{plotCyto1d,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowSet-method}}
#' @seealso \code{\link{plotCytoExprs,GatingHierarchy-method}}
#' @seealso \code{\link{plotCytoExprs,GatingSet-method}}
#'
#' @examples 
#' \dontrun{
#' plotCytoExprs(fr, transList = trans)
#' }
#'
#' @export
setMethod(plotCytoExprs, signature = "flowFrame", definition = function(x, channels = NULL, transList = NULL, mfrow = NULL, title = NULL, ...){

  # Assign x to fr
  fr <- x
  
  # Extract data for axes limits
  fr.exprs <- exprs(fr)
  
  # Missing channels
  if(is.null(channels)){
    
    channels <- BiocGenerics::colnames(fr)
    channels <- channels[channels != "Time"]
    
  }else{
    
    channels <- checkChannels(x = fr, channels = channels, plot = FALSE)
    
  }
  
  # Grid layout
  if(is.null(mfrow)){
    
    mfrow <- c(n2mfrow(length(channels))[2], n2mfrow(length(channels))[1])
    par(mfrow = mfrow)
    
  }else if(!is.null(mfrow)){
    
    if(mfrow[1] == FALSE){
      
      # Do nothing
      
    }else{
      
      par(mfrow = mfrow)
      
    }
    
  }
  
  # Title space
  par(oma = c(0,0,3,0))
  
  # Plots
  lapply(channels, function(channel){
    
    plotCyto(x = fr, channel = channel, transList = transList, mfrow = FALSE, main = NULL, ...)
    
  })
  
  # Plot title
  if(is.null(title)){
    
    title <- fr@description$GUID
  }
  mtext(title, outer = TRUE, cex = 1, font = 2)
  
  # Return defaults
  par(mfrow = c(1,1))
  par(oma = c(0,0,0,0))
  
  return(NULL)
  
})

#' Plot Population Density Distribution in All Channels - flowSet Method
#'
#' @param x object of class \code{\link[flowCore:flowSet-class]{flowSet}}.
#' @param channels a vector channels to use to construct the plots, set to all
#'   channels by default.
#' @param transList object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transList object will be used internally to ensure axes labels of the plot
#'   are appropriately transformed. The transList will NOT be applied to the
#'   flowFrame internally and should be applied to the flowFrame prior to
#'   plotting.
#' @param merge logical indicating whether flowFrames should be merged prior to
#'   plotting, set to TRUE by default.
#' @param ... additional arguments passed to \code{\link{plotCyto1d,flowFrame-method}}.
#'
#' @importFrom flowCore exprs
#' @importFrom methods as
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#' 
#' @seealso \code{\link{plotCyto1d,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,GatingHierarchy-method}}
#' @seealso \code{\link{plotCytoExprs,GatingSet-method}}
#'
#' @examples 
#' \dontrun{
#' plotCytoExprs(fs, transList = trans)
#' }
#'
#' @export
setMethod(plotCytoExprs, signature = "flowSet", definition = function(x, channels = NULL, transList = NULL, merge = TRUE, ...){
  
  # Assign x to fs
  fs <- x
  
  # Title
  if(is.null(title)){
    
    title <- "Combined Events"
    
  }
  
  # Merge?
  if(merge == TRUE){
    
    fr <- as(fs, "flowFrame")
    plotCytoExprs(x = fr, channels = channels, title = title, transList = transList, ...)
    
  }else if(merge == FALSE){
  
    plotCytoExprs(x = fs[[1]], overlay = fs[2:length(fs)], channels = channels, transList = transList, ...)
  
  }
  
  return(NULL)
  
})

#' Plot Population Density Distribution in All Channels - GatingHierarchy Method
#'
#' @param x object of class \code{\link[flowWorkspace:GatingHierarchy-class]{GatingHierarchy}}.
#' @param channels a vector channels to use to construct the plots, set to all
#'   channels by default.
#' @param parent name of the population used to construct the plot.
#' @param transList object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transList object will be used internally to ensure axes labels of the plot
#'   are appropriately transformed. The transList will NOT be applied to the
#'   flowFrame internally and should be applied to the flowFrame prior to
#'   plotting.
#' @param ... additional arguments passed to \code{\link{plotCyto1d,flowFrame-method}}.
#'
#' @importFrom flowCore exprs transformList
#' @importFrom flowWorkspace getData transformerList getTransformations
#' @importFrom grDevices n2mfrow
#' @importFrom graphics par mtext plot.new
#' @importFrom utils read.csv
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{plotCyto1d,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowSet-method}}
#' @seealso \code{\link{plotCytoExprs,GatingSet-method}}
#'
#' @examples 
#' \dontrun{
#' plotCytoExprs(gh, parent = "root", transList = trans)
#' }
#'
#' @export
setMethod(plotCytoExprs, signature = "GatingHierarchy", definition = function(x, parent = NULL, channels = NULL, transList = NULL, ...){
  
  # Parent missing
  if(is.null(parent)){
    
    stop("Please supply the name of the parent population to plot.")
    
  }
  
  # Assign x to gh
  gh <- x
  
  # Extract population
  fr <- getData(gh, parent)

  # Missing channels
  if(is.null(channels)){
    
    channels <- BiocGenerics::colnames(fr)
    channels <- channels[channels != "Time"]
    
  }else{
    
    channels <- checkChannels(x = fr, channels = channels, plot = FALSE)
    
  }
  
  # TransList
  if(is.null(transList)){
    
    trnsfrms <- lapply(channels, function(channel){getTransformations(gh, channel, only.function = TRUE)})
    names(trnsfrms) <- channels
    trnsfrms[sapply(trnsfrms, is.null)] <- NULL
    transList <- transformList(names(trnsfrms), trnsfrms)
    
  }else if(!is.null(transList) & class(transList)[1] == "transformerList"){
    
    transList <- transformList(names(transList), lapply(transList, `[[`, "transform"))
    
  }
  
  # Plots
  plotCytoExprs(x = fr, channels = channels, transList = transList, ...)
  
  return(NULL)
  
})

#' Plot Population Density Distribution in All Channels - GatingSet Method
#'
#' @param x object of class \code{\link[flowWorkspace:GatingSet-class]{GatingSet}}.
#' @param channels a vector channels to use to construct the plots, set to all
#'   channels by default.
#' @param parent name of the population used to construct the plot.
#' @param transList object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame. This
#'   transList object will be used internally to ensure axes labels of the plot
#'   are appropriately transformed. The transList will NOT be applied to the
#'   flowFrame internally and should be applied to the flowFrame prior to
#'   plotting.
#' @param ... additional arguments passed to \code{\link{plotCyto1d,flowFrame-method}}.
#'
#' @importFrom flowCore exprs transformList
#' @importFrom flowWorkspace getData transformerList getTransformations
#' @importFrom grDevices n2mfrow
#' @importFrom graphics par mtext plot.new
#' @importFrom utils read.csv
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{plotCyto1d,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowFrame-method}}
#' @seealso \code{\link{plotCytoExprs,flowSet-method}}
#' @seealso \code{\link{plotCytoExprs,GatingHierarchy-method}}
#'
#' @examples 
#' \dontrun{
#' plotCytoExprs(gs, parent = "root", transList = trans)
#' }
#'
#' @export
setMethod(plotCytoExprs, signature = "GatingSet", definition = function(x, parent = NULL, channels = NULL, transList = NULL, ...){
  
  # Parent missing
  if(is.null(parent)){
    
    stop("Please supply the name of the parent population to plot.")
    
  }
  
  # Assign x to gs
  gs <- x
  
  # Extract population
  fs <- getData(gs, parent)
  
  # Missing channels
  if(is.null(channels)){
    
    channels <- BiocGenerics::colnames(fs[[1]])
    channels <- channels[channels != "Time"]
    
  }else{
    
    channels <- checkChannels(x = fs, channels = channels, plot = FALSE)
    
  }
  
  # TransList
  if(is.null(transList)){
    
    trnsfrms <- lapply(channels, function(channel){getTransformations(gs[[1]], channel, only.function = TRUE)})
    names(trnsfrms) <- channels
    trnsfrms[sapply(trnsfrms, is.null)] <- NULL
    transList <- transformList(names(trnsfrms), trnsfrms)
    
  }else if(!is.null(transList) & class(transList)[1] == "transformerList"){
    
    transList <- transformList(names(transList), lapply(transList, `[[`, "transform"))
    
  }
  
  # Plots
  plotCytoExprs(x = fs, channels = channels, transList = transList, ...)
  
  return(NULL)
  
})