# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Repel overlapping labels
#'
#' Iteratively move labels apart to minimize overlap.
#'
#' @param x x-coordinates
#' @param y y-coordinates
#' @param w label widths
#' @param h label heights
#' @param xlim plot x-limits
#' @param ylim plot y-limits
#' @param iter maximum iterations
#' @param force repulsion force factor
#'
#' @noRd
cpp_repel <- function(x, y, w, h, xlim, ylim, iter = 2000L, force = 1.0, pad = as.numeric( c(0.0, 0.0))) {
    .Call(`_CytoExploreR_cpp_repel`, x, y, w, h, xlim, ylim, iter, force, pad)
}

rcpp_median_inplace <- function(x) {
    .Call(`_CytoExploreR_rcpp_median_inplace`, x)
}

median_cpp <- function(x) {
    .Call(`_CytoExploreR_median_cpp`, x)
}

col_median_cpp <- function(x) {
    .Call(`_CytoExploreR_col_median_cpp`, x)
}

binned_median_cpp <- function(x, y, n_bins) {
    .Call(`_CytoExploreR_binned_median_cpp`, x, y, n_bins)
}

geometric_median_cpp <- function(x, eps = 1e-5, maxiter = 100L) {
    .Call(`_CytoExploreR_geometric_median_cpp`, x, eps, maxiter)
}

geomean_cpp <- function(x) {
    .Call(`_CytoExploreR_geomean_cpp`, x)
}

col_geomean_cpp <- function(x) {
    .Call(`_CytoExploreR_col_geomean_cpp`, x)
}

sd_cpp <- function(x) {
    .Call(`_CytoExploreR_sd_cpp`, x)
}

col_sd_cpp <- function(x) {
    .Call(`_CytoExploreR_col_sd_cpp`, x)
}

mad_cpp <- function(x) {
    .Call(`_CytoExploreR_mad_cpp`, x)
}

col_mad_cpp <- function(x) {
    .Call(`_CytoExploreR_col_mad_cpp`, x)
}

rsd_cpp <- function(x) {
    .Call(`_CytoExploreR_rsd_cpp`, x)
}

col_rsd_cpp <- function(x) {
    .Call(`_CytoExploreR_col_rsd_cpp`, x)
}

mean_cpp <- function(x) {
    .Call(`_CytoExploreR_mean_cpp`, x)
}

col_mean_cpp <- function(x) {
    .Call(`_CytoExploreR_col_mean_cpp`, x)
}

quantile_cpp <- function(x, probs) {
    .Call(`_CytoExploreR_quantile_cpp`, x, probs)
}

col_quantile_cpp <- function(x, probs) {
    .Call(`_CytoExploreR_col_quantile_cpp`, x, probs)
}

neg_quantile_cpp <- function(x, probs) {
    .Call(`_CytoExploreR_neg_quantile_cpp`, x, probs)
}

cv_cpp <- function(x) {
    .Call(`_CytoExploreR_cv_cpp`, x)
}

col_cv_cpp <- function(x) {
    .Call(`_CytoExploreR_col_cv_cpp`, x)
}

rcv_cpp <- function(x) {
    .Call(`_CytoExploreR_rcv_cpp`, x)
}

col_rcv_cpp <- function(x) {
    .Call(`_CytoExploreR_col_rcv_cpp`, x)
}

range_cpp <- function(x) {
    .Call(`_CytoExploreR_range_cpp`, x)
}

col_range_cpp <- function(x) {
    .Call(`_CytoExploreR_col_range_cpp`, x)
}

min_cpp <- function(x) {
    .Call(`_CytoExploreR_min_cpp`, x)
}

col_min_cpp <- function(x) {
    .Call(`_CytoExploreR_col_min_cpp`, x)
}

max_cpp <- function(x) {
    .Call(`_CytoExploreR_max_cpp`, x)
}

col_max_cpp <- function(x) {
    .Call(`_CytoExploreR_col_max_cpp`, x)
}

skewness_cpp <- function(x) {
    .Call(`_CytoExploreR_skewness_cpp`, x)
}

col_skewness_cpp <- function(x) {
    .Call(`_CytoExploreR_col_skewness_cpp`, x)
}

scale_cpp <- function(x, type = "range", probs = NULL) {
    .Call(`_CytoExploreR_scale_cpp`, x, type, probs)
}

col_scale_cpp <- function(x, type = "range", probs = NULL) {
    .Call(`_CytoExploreR_col_scale_cpp`, x, type, probs)
}

rescale_cpp <- function(x, scale = NULL, limits = NULL) {
    .Call(`_CytoExploreR_rescale_cpp`, x, scale, limits)
}

col_rescale_cpp <- function(x, scale = NULL, limits = NULL) {
    .Call(`_CytoExploreR_col_rescale_cpp`, x, scale, limits)
}

purity_cpp <- function(x) {
    .Call(`_CytoExploreR_purity_cpp`, x)
}

row_purity_cpp <- function(x) {
    .Call(`_CytoExploreR_row_purity_cpp`, x)
}

vwqr_cpp <- function(data, tau = 0.5, max_iter = 10L, tol = 1e-6, residual_type = "both", grid_size = 100L, span = 0.75) {
    .Call(`_CytoExploreR_vwqr_cpp`, data, tau, max_iter, tol, residual_type, grid_size, span)
}

wasserstein1d_cpp <- function(a, b, p = 1.0, wa_ = NULL, wb_ = NULL) {
    .Call(`_CytoExploreR_wasserstein1d_cpp`, a, b, p, wa_, wb_)
}

