name: CytoExploreR Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: CytoExploreR Docker Build & Push
      run: |
        export VERSION=$(grep Version DESCRIPTION | awk '{print $2}')
        export VERSION="v$VERSION"
        docker build -t dhammill/cytoexplorer:$VERSION .
        docker push dhammill/cytoexplorer:$VERSION 
