name: CytoExploreR Devel Docker

on:
  push:
    branches: [ refine ]
  pull_request:
    branches: [ refine ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: QEMU
      uses: docker/setup-qemu-action@v1
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: CytoExploreR Docker Build & Push
      run: |
        export VERSION=$(grep Version DESCRIPTION | awk '{print $2}')
        export VERSION="v$VERSION"
        docker buildx build --platform linux/amd64,linux/arm64 -t dhammill/cytoexplorer-devel:$VERSION -t dhammill/cytoexplorer-devel:latest --push .
