name: CytoExploreR Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: QEMU
      uses: docker/setup-qemu-actions@v1
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Hub Login
      uses: docker/login-actions@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Image Tag
      run: |
        export DOCKER_IMAGE_VERSION=$(grep Version DESCRIPTION | awk '{print $2}')
        export DOCKER_IMAGE_VERSION="v${DOCKER_IMAGE_VERSION}"
    - name: CytoExploreR Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${ DOCKER_IMAGE_VERSION }
